local r=fu:GetResolve();local pm=r:GetProjectManager();local p=pm:GetCurrentProject();assert(not p:IsRenderingInProgress());if p:GetName()~='MOT-UGC-YAPPER-01 v7 V3 20260910' then assert(pm:SaveProject());p=pm:LoadProject('MOT-UGC-YAPPER-01 v7 V3 20260910');assert(p) end
local old=nil;for i=1,p:GetTimelineCount() do local x=p:GetTimelineByIndex(i);if x:GetName()=='v10 FINAL - centered square overlays' then old=x end;assert(x:GetName()~='v11 FINAL - wardrobe and cramping','V11 already exists; inspect') end;assert(old);p:SetCurrentTimeline(old);local t=old:DuplicateTimeline('v11 FINAL - wardrobe and cramping');assert(t);p:SetCurrentTimeline(t);local mp=p:GetMediaPool()
local jobs={{s=502,e=622,offset=0,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/woman-cramping-square.mov",overlay=true},{s=675,e=765,offset=30,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/normalized/unfinished-dinner.mp4",overlay=false},{s=847,e=907,offset=30,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/normalized/loose-jeans.mp4",overlay=false},{s=1013,e=1103,offset=30,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/normalized/kitchen-wait.mp4",overlay=false},{s=1527,e=1617,offset=30,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/normalized/fiber-stirring.mp4",overlay=false},{s=1881,e=1971,offset=30,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/normalized/morning-heavy.mp4",overlay=false},{s=1986,e=2044,offset=30,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/normalized/pharmacy.mp4",overlay=false},{s=2803,e=2893,offset=30,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/normalized/research.mp4",overlay=false},{s=6101,e=6171,offset=0,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/normalized/routine.mp4",overlay=false},{s=6354,e=6444,offset=180,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/normalized/dinner.mp4",overlay=false},{s=6753,e=6843,offset=30,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/normalized/mirror.mp4",overlay=false},{s=7091,e=7168,offset=30,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/normalized/leaving.mp4",overlay=false},{s=7256,e=7346,offset=30,path="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v11/normalized/clearing.mp4",overlay=false}}
for _,j in ipairs(jobs) do
 local props={ZoomX=1,ZoomY=1,Pan=0,Tilt=0,CropTop=0,CropBottom=0,CropLeft=0,CropRight=0};local target=nil
 for _,c in ipairs(t:GetItemListInTrack('video',2)) do if c:GetStart()==j.s and c:GetEnd()==j.e then target=c end end
 if not j.overlay then assert(target);for k,_ in pairs(props) do props[k]=target:GetProperty(k) end;assert(t:DeleteClips({target},false)) else assert(not target);props.ZoomX=2/3;props.ZoomY=2/3 end
 local m=mp:ImportMedia({j.path})[1];assert(m,'Import '..j.path);local c=mp:AppendToTimeline({{mediaPoolItem=m,startFrame=j.offset,endFrame=j.offset+j.e-j.s,recordFrame=j.s,trackIndex=2,mediaType=1}})[1];assert(c);assert(c:SetProperty(props));assert(c:GetStart()==j.s and c:GetEnd()==j.e);print('V11_REPLACED',j.s,j.e,c:GetName())
end
assert(t:GetEndFrame()==8327);assert(#t:GetItemListInTrack('video',1)==16);assert(#t:GetItemListInTrack('video',2)==22);assert(#t:GetItemListInTrack('video',3)==229);assert(#t:GetItemListInTrack('audio',1)==16);assert(pm:SaveProject());print('V11_ASSEMBLED',t:GetName(),t:GetEndFrame())
