local r=fu:GetResolve();local pm=r:GetProjectManager();local p=pm:GetCurrentProject();assert(p:GetName()=='MOT-UGC-YAPPER-01 v7 V3 20260910');assert(not p:IsRenderingInProgress())
local base=nil;local prior=nil;local src=nil;local t=nil
for i=1,p:GetTimelineCount() do local q=p:GetTimelineByIndex(i);local n=q:GetName();if n=='v18 FINAL - Michelle V3 MiraLAX' then base=q elseif n=='v21 FINAL - 1.2x Michelle' then prior=q elseif n=='v22 SOURCE - toilet cramping' then src=q elseif n=='v22 FINAL - 1.2x toilet cramping' then t=q end end
assert(base and prior and base:GetEndFrame()==9431 and prior:GetEndFrame()==7859)
if not src then assert(p:SetCurrentTimeline(base));src=base:DuplicateTimeline('v22 SOURCE - toilet cramping');assert(src) end
assert(p:SetCurrentTimeline(src));local mp=p:GetMediaPool();local item=nil
for _,c in ipairs(src:GetItemListInTrack('video',2)) do if c:GetStart()==2779 and c:GetEnd()==2856 then item=c elseif c:GetStart()<2856 and c:GetEnd()>2779 then error('Unexpected overlapping source insert') end end
if not item then local m=mp:ImportMedia({"/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v22/toilet-cramping-30fps.mp4"})[1];assert(m);item=mp:AppendToTimeline({{mediaPoolItem=m,startFrame=0,endFrame=77,recordFrame=2779,trackIndex=2,mediaType=1}})[1];assert(item);assert(item:SetProperty({ZoomX=1,ZoomY=1,Pan=0,Tilt=0})) end
assert(item:GetStart()==2779 and item:GetEnd()==2856);assert(src:GetEndFrame()==9431);assert(#src:GetItemListInTrack('video',2)==27);assert(#src:GetItemListInTrack('video',3)==227)
if not t then t=mp:CreateEmptyTimeline('v22 FINAL - 1.2x toilet cramping');assert(t);assert(p:SetCurrentTimeline(t));t:SetStartTimecode('00:00:00:00');assert(mp:AppendToTimeline({{mediaPoolItem=src:GetMediaPoolItem(),startFrame=0,endFrame=9431,recordFrame=0}})) end
assert(p:SetCurrentTimeline(t));local v=t:GetItemListInTrack('video',1)[1];local a=t:GetItemListInTrack('audio',1)[1]
if math.abs(v:GetSpeed().Percentage-100)<.0001 and v:GetEnd()==9431 then assert(v:SetSpeed({Percentage=120,PitchCorrection=true,RippleTimeline=true})) end
assert(v:SetProperty('RetimeProcess',1));assert(math.abs(v:GetSpeed().Percentage-120)<.0001 and math.abs(a:GetSpeed().Percentage-120)<.0001 and a:GetSpeed().PitchCorrection);assert(t:GetEndFrame()==7859 and v:GetEnd()==7859 and a:GetEnd()==7859);assert(base:GetEndFrame()==9431 and prior:GetEndFrame()==7859);assert(pm:SaveProject());print('V22_VERIFIED',t:GetEndFrame(),item:GetStart(),item:GetEnd());dump(a:GetSpeed())
assert(t:Export("/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v22/deliverables/Motilli-Unbranded-VSL-v22-1.2x-toilet-broll.drt",r.EXPORT_DRT));assert(pm:ExportProject(p:GetName(),"/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v22/deliverables/Motilli-Unbranded-VSL-v22-1.2x-toilet-broll.drp"));p:SetCurrentRenderMode(1);p:SetRenderSettings({ExportVideo=true,ExportAudio=true});assert(p:SetCurrentRenderFormatAndCodec('mp4','H264'));assert(p:SetRenderSettings({TargetDir="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v22/deliverables",CustomName='Motilli-Unbranded-VSL-v22-1.2x-toilet-broll',SelectAllFrames=true,FormatWidth=1080,FormatHeight=1920,FrameRate=30,ExportVideo=true,ExportAudio=true,AudioCodec='aac',AudioSampleRate=48000,VideoQuality=16000,NetworkOptimization=true}));local job=p:AddRenderJob();assert(job);print('V22_RENDER_JOB',job);assert(pm:SaveProject());p:StartRendering(job)
