from pathlib import Path
import json,sys
P=Path(__file__).resolve().parent;R=P/'resolve-speed110';sys.path.insert(0,str(P/'resolve-gringo-aligned'));from run_lua import run
s='local output=[=['+str(R)+']=]\nlocal target=[=['+str(P/'exports')+']=]\n'+r'''
local pm=r:GetProjectManager();local p=pm:GetCurrentProject();assert(p:GetName()=="VEL_Weekender_Haaland_20260912");assert(not p:IsRenderingInProgress());local t=p:GetCurrentTimeline();assert(t:GetName()=="Weekender-Haaland-Gringo-Natural-AvatarV-110-v1");local v=t:GetItemListInTrack("video",1)[1];local a=t:GetItemListInTrack("audio",1)[1];assert(math.abs(v:GetSpeed().Percentage-110)<0.0001);assert(math.abs(a:GetSpeed().Percentage-110)<0.0001);assert(v:GetSpeed().PitchCorrection and a:GetSpeed().PitchCorrection);assert(v:GetEnd()==1040 and a:GetEnd()==1040)
assert(pm:SaveProject());assert(t:Export(output.."/Weekender-Haaland-Gringo-Natural-AvatarV-110-v1.drt",r.EXPORT_DRT));for i=1,p:GetTimelineCount() do local z=p:GetTimelineByIndex(i);if z:GetName()=="Weekender-Haaland-Gringo-PausesClosed-v1" then assert(z:Export(output.."/Weekender-Haaland-Gringo-PausesClosed-v1.drt",r.EXPORT_DRT)) end end;assert(pm:ExportProject(p:GetName(),output.."/VEL-Weekender-Haaland-Gringo-Speed110.drp",true))
assert(p:SetCurrentRenderFormatAndCodec("mp4","H264"));assert(p:SetCurrentRenderMode(1));assert(p:SetRenderSettings({SelectAllFrames=true,TargetDir=target,CustomName="Weekender-Haaland-Gringo-Natural-AvatarV-110-NoGaps",ExportVideo=true,ExportAudio=true,FormatWidth=1080,FormatHeight=1920,FrameRate=30,VideoQuality=16000,AudioCodec="aac",AudioSampleRate=48000,NetworkOptimization=true}));assert(pm:SaveProject());local id=p:AddRenderJob();assert(id);assert(p:StartRendering({id}));return {project=p:GetName(),timeline=t:GetName(),frames=t:GetEndFrame(),video=v:GetSpeed(),audio=a:GetSpeed(),saved=true,job=id,started=true}
'''
o=run(s,30);(R/'render-receipt.json').write_text(json.dumps(o,indent=2));print(o);assert o['ok']
