from pathlib import Path
import json,hashlib
P=Path(__file__).resolve().parent;B=P.parent;root=P.parents[4]
d=json.loads(Path('/tmp/haaland-before-natural.json').read_text());S=json.loads((P/'resolve-natural/aligned-scenes.json').read_text());spec=json.loads((B/'storyboard/spec.json').read_text())
def rel(p):return str(p.relative_to(root))
d['context_notes']+=' User September12 rejected robotic voice and explicitly requested a fresh reference clone, Eleven v3 Natural and HeyGen Avatar V. Completed fresh permitted clone 0W4ZWcNHJi6CkQNkVY4H; selected pronunciation-corrected Natural stability0.5 original-speed43.68s take; explicit avatar_v video084f4167012d95d29ff8a6f99f05f8ad. Exact approved narration retained. Current Resolve timeline Weekender-Haaland-Natural-AvatarV-v2 and45.70s Natural-AvatarV export supersede earlier Creative take/v6 export; originals preserved. Cuts and31phrase captions realigned; all31captions+4hook labels centered within2.5px horizontally and2.1px vertically at1080width. Export has1371decodedframes, no detectedoffline/black/greenscreenframes,0ms audio offset. S11 generated clip rejected after direct inspection found invented zipper; selected actual owner-shot IMG_4051.MOV8.50–13.333s shows actual slip pocket. Overlay clearance corrected. Public Cut Room actual first frames refreshed. Detailed evidence and limits in production/qa-natural/final-review.md; no human approval or measured ad performance claimed.'
for a in d['artifacts']:
 if a['id']=='PLAN':a['status']='current Natural narration aligned; revision rationale and exact cut times saved'
 if a['id']=='SCRIPT':a['status']='selected exact narration preserved'
 if a['id']=='VOICE-STATE':a['status']='fresh permitted reference clone; Eleven v3 Natural0.5; explicit Avatar V completed'
 if a['id'] in ['FINAL-MP4','RESOLVE-PROJECT','RESOLVE-TIMELINE','PRODUCTION-QA','HEYGEN-RECEIPT','VOICE-CLONE','RESOLVE-RECEIPT','RENDERED-BOARD']:a['status']='historical; superseded by Natural / Avatar V revision; original preserved'
artifacts=[('NATURAL-MP4',P/'exports/Weekender-Haaland-Natural-AvatarV.mp4','export','current selected; rendered and inspected'),('NATURAL-VOICE',P/'voice-natural-corrected/narration-natural.mp3','voiceover','selected unchanged narration; original speed; pronunciation corrected'),('NATURAL-CLONE',P/'voice-natural/clone-receipt.json','status','fresh clone from permitted actual reference'),('NATURAL-VOICE-REQUEST',P/'voice-natural-corrected/tts-request.json','status','eleven_v3 Natural stability0.5'),('NATURAL-AVATAR-REQUEST',P/'heygen-natural-corrected/request.json','status','explicit engine avatar_v'),('NATURAL-AVATAR-STATUS',P/'heygen-natural-corrected/state.json','status','completed video084f4167012d95d29ff8a6f99f05f8ad'),('NATURAL-RESOLVE-PROJECT',P/'resolve-natural/VEL-Weekender-Haaland-Natural.drp','edit','current native project exported'),('NATURAL-RESOLVE-TIMELINE',P/'resolve-natural/Weekender-Haaland-Natural-AvatarV-v2.drt','edit','current native timeline exported'),('NATURAL-RESOLVE-RECEIPT',P/'resolve-natural/final-project-receipt.json','status','actual in-app API verified; render Complete'),('NATURAL-QA',P/'qa-natural/final-review.md','status','current rendered media evidence and review limitations'),('NATURAL-REFERENCE-COMPARISON',B/'edit/reference-comparison-natural.md','reference','observed reference transfer and deliberate differences'),('NATURAL-BOARD',B/'storyboard/natural-board-receipt.json','status','13actual selected first frames published and verified')]
for ident,path,role,status in artifacts:
 assert path.exists(),path
 d['artifacts']=[a for a in d['artifacts'] if a['id']!=ident];d['artifacts'].append(dict(id=ident,path=rel(path),role=role,status=status))
for i,s in enumerate(S):
 b=next(b for b in d['beats'] if b['id']==s['id']);beat=spec['timelines'][0]['beats'][i]
 medium='Google Omni photographic motion with HeyGen presenter' if s['id'] in ['S04','S07','S12'] else 'Actual owner-shot product demonstration with HeyGen presenter' if s['id']=='S11' else 'Distinct photographic still with HeyGen presenter' if s['id']!='S13' else 'Clean product still; no presenter or text'
 b.update(duration=(s['end']-s['start'])/30,action=beat['visual'],why_here=beat['note'],transition_in='Direct cut on selected Natural narration alignment',transition_out='Two-second clean end hold' if s['id']=='S13' else 'Direct cut on next spoken cue',medium=medium,source_route='See production/resolve-natural/manifest.json for exact media and source ranges; original files preserved.')
 a=next(a for a in d['assets'] if a['id']==b['asset_id']);f=Path(beat['frame']);a.update(path=rel(f),sha256=hashlib.sha256(f.read_bytes()).hexdigest(),source_identity='Actual first frame from current Natural / Avatar V Resolve export; natural-board-receipt.json',inspection='Current selected exported composition inspected; consecutive cut pairs and every caption center checked. Scope and limitations in production/qa-natural/final-review.md. Physical scale not certified.')
d['operational']['rework_count']=d['operational'].get('rework_count',0)+1
Path('/tmp/haaland-natural-save.json').write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
sp=B/'storyboard/voice/state.json';state=json.loads(sp.read_text());state.update(status='fresh_reference_clone_natural_avatar_v_selected',voice_id='0W4ZWcNHJi6CkQNkVY4H',selected_take=rel(P/'voice-natural-corrected/narration-natural.mp3'),model_id='eleven_v3',preset='Natural',stability=0.5,heygen_video_id='084f4167012d95d29ff8a6f99f05f8ad',heygen_engine='avatar_v',final_duration_seconds=45.7);sp.write_text(json.dumps(state,indent=2)+'\n')
