from pathlib import Path
import json,hashlib
P=Path(__file__).resolve().parent;B=P.parent;root=P.parents[4];d=json.loads(Path('/tmp/haaland-current-record.json').read_text());S=json.loads((P/'resolve/aligned-scenes.json').read_text());spec=json.loads((B/'storyboard/spec.json').read_text())
def rel(p):return str(p.relative_to(root))
d['production'].update(presenter_model='HeyGen Avatar V',voice_provider='ElevenLabs',voice_take=rel(P/'voice/narration-v2-creative.mp3'),resolve_project='VEL_Weekender_Haaland_20260912',resolve_timeline='Weekender-Haaland-HeyGen-v6',export=rel(P/'exports/Weekender-Haaland-final.mp4'),duration_seconds=43.3)
d['approvals'].append({'id':'USER-PRODUCTION-20260912','scope':'Reference-speaker voice clone with confirmed permission/lawful use; HeyGen original talking-head avatar; DaVinci Resolve ad assembly.','source':'User conversation September 12 2026: yes to explicit permission question; use heygen for talking head avatar. fix that.','date':'2026-09-12'})
d['context_notes']+=' Production completed September12: prior voice permission gate resolved by explicit user yes. Selected clone take2 drives original HeyGen avatar; 43.3s Resolve edit, exact narration unchanged. S04/S11/S12 restrained revised Omni actions, S07 original inspected Omni motion, S06 corrected still after two failed requests. Offline numbered PNG sequences replaced with digit-free still paths. Continuous Resolve-keyed presenter master and explicit source timecode mapping fix edit-side sync. Caption text/background dimensions and padding corrected. Final MP4/DRP/DRT saved; actual rendered first frames and voice-aligned timings published and verified in Cut Room. Automated review and source-frame/audio checks documented in production/qa; no human approval or campaign performance claimed.'
for a in d['artifacts']:
 if a['id']=='VOICE-STATE':a['status']='permission_confirmed; clone take2 selected; HeyGen original avatar generated and placed'
artifacts=[('FINAL-MP4',P/'exports/Weekender-Haaland-final.mp4','export','rendered; decode and timing checks completed'),('RESOLVE-PROJECT',P/'resolve/VEL-Weekender-Haaland.drp','edit','exported native Resolve project'),('RESOLVE-TIMELINE',P/'resolve/Weekender-Haaland-HeyGen-v6.drt','edit','exported final native timeline'),('PRODUCTION-QA',P/'qa/final-review.md','status','documented technical and visual checks; human review not claimed'),('HEYGEN-RECEIPT',P/'heygen/state.json','status','completed original avatar with selected cloned voice'),('VOICE-CLONE',P/'voice/clone-receipt.json','status','confirmed-permission voice clone created'),('OMNI-RECEIPT',P/'omni/broll-v2-status.json','status','three revised motion clips selected; S06 failed and still retained'),('RESOLVE-RECEIPT',P/'resolve/final-project-receipt.json','status','actual in-app API verified and final export complete'),('RENDERED-BOARD',B/'storyboard/rendered-board-receipt.json','status','actual rendered first frames published and public assets verified')]
for ident,path,role,status in artifacts:
 d['artifacts']=[a for a in d['artifacts'] if a['id']!=ident];d['artifacts'].append(dict(id=ident,path=rel(path),role=role,status=status))
for i,s in enumerate(S):
 b=next(b for b in d['beats'] if b['id']==s['id']);beat=spec['timelines'][0]['beats'][i];b.update(duration=(s['end']-s['start'])/30,action=beat['visual'],why_here=beat['note'],transition_in='Direct cut on selected narration alignment',transition_out='Direct cut; S13 ends with two-second clean hold',medium='Google Omni photographic motion with HeyGen presenter' if s['id'] in ['S04','S07','S11','S12'] else 'Distinct photographic still with HeyGen presenter' if s['id']!='S13' else 'Clean product still; no presenter or text',source_route='See production/resolve/manifest.json for exact selected media; original provider files preserved.')
 a=next(a for a in d['assets'] if a['id']==b['asset_id']);f=Path(beat['frame']);a.update(path=rel(f),sha256=hashlib.sha256(f.read_bytes()).hexdigest(),source_identity='Actual first frame from final Resolve export; rendered-board-receipt.json',inspection='Selected final composition viewed; source motion sampled and whole export reviewed by model; exact limitations in production/qa/final-review.md. Physical scale not certified.')
d['operational']['rework_count']=d['operational'].get('rework_count',0)+1
Path('/tmp/haaland-save-record.json').write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
statep=B/'storyboard/voice/state.json';state=json.loads(statep.read_text());state.update(status='selected_voice_and_heygen_rendered',selected_take=rel(P/'voice/narration-v2-creative.mp3'),heygen_video_id='91af42fd1f2bbfc9664ef97321ec8b0e',final_duration_seconds=43.3);statep.write_text(json.dumps(state,indent=2))
