from pathlib import Path
import json,hashlib,sys
P=Path(__file__).resolve().parent;R=P/'tight';Q=R/'qa';root=next(p for p in P.parents if (p/'_engine/ad-system/store.py').exists())
sys.path.insert(0,str(root/'_engine/ad-system'));from store import Store;from obsidian_memory import remember
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
movie=P/'exports/Eleanor-EuropeanTravel-Tight.mp4';drp=P/'exports/Eleanor-EuropeanTravel-Tight.drp'
probe=json.loads((Q/'probe.json').read_text());v=next(s for s in probe['streams'] if s['codec_type']=='video')
assert (v['width'],v['height'],v['r_frame_rate'],int(v['nb_frames']))==(1080,1920,'30/1',2120)
audio=json.loads((Q/'audio-verification.json').read_text());assert audio['audio_identity_and_timing_pass'] and not audio['residual_internal_silences_over_0_2s']
assert json.loads((R/'render-status.json').read_text())['result']['status']['JobStatus']=='Complete'
board=json.loads((Q/'cutroom-verification.json').read_text());assert board['cloud_matches_local'] and board['approved_script_exact']
manifest=json.loads((R/'manifest.json').read_text());assert ' '.join(c['text'] for c in manifest['captions'])==' '.join((P.parent/'script-v1.txt').read_text().split())
machine=json.loads((Q/'perceptual-review.json').read_text());sha=digest(movie);assert machine['source_sha256']==sha
assert ' '.join(machine['heard_transcript'].split())==' '.join((P.parent/'script-v1.txt').read_text().split())
reconciliation={'raw_machine_verdict':{'must_fix':machine['must_fix'],'usable_for_review':machine['usable_for_review']},'audio_observation':'Machine actual-video review reported exact transcript, no audible join problems, no remaining dead spaces, good pacing and good lip sync. All 28 retained intervals independently correlate above 0.99999 at zero lag using 48 kHz sample comparisons.','layout_reconciliation':'Machine treated the requested enlargement as a future operation, although this reviewed export already has zoom 0.33 versus prior 0.28. Native full-frame samples show the left sleeve at frame edge and torso meeting bottom edge. Inspected S04/S06/S07/S09 samples retain bag readability; some lower-left proximity/partial overlap is inherent to presenter coverage, without obscuring the principal bag view. Direct frame at 69s (cta-spoken.jpg) shows shop captions above the graphic and presenter beside it, contradicting the machine below-graphic/collision claim. All nine consecutive scene boundary pairs were directly inspected; no missing/offline shot was observed.','decision':'Agent technical review passes for the requested pacing/layout revision based on direct visual evidence and audio checks. Raw machine flags preserved rather than represented as a model pass.','limits':'Sampled visual review and 4fps machine review are not frame-exhaustive or human approval. Small overlaps between foreground presenter and background are possible; visual hierarchy remains readable in inspected samples.'}
(Q/'review-reconciliation.json').write_text(json.dumps(reconciliation,indent=2)+'\n')
cutmap=json.loads((R/'cut-map.json').read_text())
receipt={'status':'completed review edit','project':'VEL_Eleanor_EuropeanTravel_Natural110_20260912','timeline':'Eleanor-EuropeanTravel-Tight','video_seconds':2120/30,'container_seconds':float(probe['format']['duration']),'frames':2120,'fps':30,'width':1080,'height':1920,'quiet_gap_cuts':len(cutmap['remove']),'removed_internal_seconds':cutmap['removed_internal_seconds'],'removed_total_seconds':cutmap['removed_total_seconds'],'presenter_layout':manifest['presenter_layout'],'presenter_size_increase_percent':(.33/.28-1)*100,'presenter_items':manifest['presenter_items'],'audio_items':manifest['audio_items'],'voice':'Existing ElevenLabs Woman Over 40 / Natural / synthesis speed 1.1; quiet-gap removal only, no extra speed change','captions':len(manifest['captions']),'approved_caption_words_exact':True,'full_audio_video_decode':'passed','audio_identity_and_timing_pass':True,'residual_internal_silences_over_0_2s':[],'visual_review':'Native scene samples, actual 69s CTA frame and all nine consecutive scene boundary pairs inspected. Full 4fps machine video/audio review retained with direct-visual reconciliation of inaccurate layout flags.','cutroom_url':board['url'],'files':[],'limits':['Technical review is not human approval or campaign clearance.','Source-photo commercial reuse remains unverified.','Product fidelity source-relative; physical scale unverified.','Paris retains selected still and planned crop.']}
for f in [movie,drp]:receipt['files'].append({'path':str(f.relative_to(root)),'bytes':f.stat().st_size,'sha256':digest(f)})
(Q/'delivery-verification.json').write_text(json.dumps(receipt,indent=2)+'\n')
settingspath=P/'production-settings.json';settings=json.loads(settingspath.read_text());settings.update({'resolve_timeline':'Eleanor-EuropeanTravel-Tight','presenter_layout':manifest['presenter_layout'],'timeline_frames':2120,'timeline_seconds':2120/30,'quiet_gap_cut_map':str((R/'cut-map.json').relative_to(root)),'resolve_audio':'Selected exact MP3 decoded to PCM; 27 quiet gaps removed with matching presenter cuts, no additional speed change'});settingspath.write_text(json.dumps(settings,indent=2)+'\n')
plan=P.parent/'edit/editing-plan.md'
with plan.open('a') as f:f.write('\nFinal tight-revision QA: native Resolve export completed (2120 frames, 70.667 s). Full audio/video decode passed. All 28 retained audio intervals match source at zero lag with correlation >0.99999; no internal quiet gaps over 0.2 s at -40 dBFS. Exact words and all 76 caption phrases preserved. Full native scene samples, all nine consecutive scene boundary pairs and actual spoken CTA frame inspected. Presenter zoom 0.33, pan -361.8, tilt -821 meets left/bottom frame edges. CTA starts 68.30 s, with final captions above the graphic. Raw model layout flags were reconciled against direct frame evidence; see production/tight/qa/review-reconciliation.json. Cut Room now shows actual revised export frames; cloud JSON and all 30 images verified. This is technical review, not human approval.\n')
st=Store();r=st.get('VELA-72dfab2c0c6d');assert r['stage']=='review'
for ident,path,role,status in [('TIGHT-MAP',R/'cut-map.json','editing-plan','completed actual silence-cut map; same intervals applied to voice/presenter'),('TIGHT-EXPORT',movie,'export','completed tight review edit'),('TIGHT-DRP',drp,'project','isolated native Resolve Tight timeline; earlier versions preserved'),('TIGHT-QA',Q/'delivery-verification.json','status','technical review complete; raw machine flags reconciled against actual frames'),('TIGHT-BOARD',Q/'cutroom-verification.json','status','cloud board and 30 actual/reference images verified')]:
 r['artifacts']=[a for a in r['artifacts'] if a['id']!=ident];r['artifacts'].append({'id':ident,'path':str(path.relative_to(root)),'role':role,'status':status})
scenes={s['id']:s for s in json.loads((R/'aligned-scenes.json').read_text())}
for b in r['beats']:
 s=scenes[b['id']];assert b['line']==s['line'];b['duration']=s['duration'];b['cut_cue']=f"Tight narration alignment: {s['start']:.3f}s–{s['end']:.3f}s at 30 fps; see exact shared cut map."
 b['transition_out']='Direct cut at next spoken scene cue.' if b['id']!='S10' else 'CTA during shop invitation at 68.30s; about 0.2s final visual finish.'
 b['style_fit']=b['style_fit'].replace('Timing provisional until final voice alignment.','Aligned to final retained narration intervals.')
 for key in ['viewer_response','why_here','why_line']:b[key]=b[key].replace('Hold two seconds after speech','Show CTA during spoken shop invitation, with about 0.2 seconds after speech')
 if b['id'] in ['S05','S07','S09']:
  b['source_route']='Selected GPT Image 2 first frame and completed Google Omni motion source; existing source timing cut using shared quiet-gap map.'
  b['medium']='Phone-style Google Omni motion with keyed HeyGen presenter'
 else:b['source_route']=b['source_route'].replace('Optional Google Omni motion later, not generated.','Selected still retained in final edit.')
summary='September 12 user-requested dead-space/corner revision complete: 27 internal quiet-gap cuts removed 8.833s plus 1.8s from ending. New Tight Resolve export 2120frames/70.667s; presenter zoom0.33 versus0.28 (17.86% larger), pan-361.8 tilt-821, flush lower-left. Original HeyGen and ElevenLabs Woman Over40/Natural/synthesis1.1 sources retained; all28 audio/presenter intervals cut together, no extra speed change. Exact244 words/76captions retained. Full decode passed, zero-lag audio correlations >0.99999, no internal quiet gaps>0.2s. All9scene boundaries inspected. Raw4fps machine review approved transcript/pacing/lipsync but inaccurately described future enlargement and CTA captions below graphic; native frames contradict these layout flags, documented in reconciliation. Revised Cut Room frames and30cloud images verified. MP4 and DRP delivered; previous versions preserved. Technical review only, not human approval or commercial source-photo clearance.'
r['context_notes']+=' '+summary;r['calibration']['next_action']='User review of completed 70.67-second Tight revision; source-photo clearance still required before campaign use.'
r=st.save(r,r['revision'],'Complete dead-space removal and larger flush-corner HeyGen presenter revision');rev=r['revision']
review=st.add_review(r['id'],'automated',{'scope':'finished-media-technical','verdict':'PASS','artifact_path':str(movie.relative_to(root)),'artifact_sha256':sha,'receipt_path':str((Q/'delivery-verification.json').relative_to(root)),'notes':'Agent technical review, not human approval. Raw machine layout flags reconciled against actual native frames; audio checks and exact narration pass.'},rev)
export=st.register_export(r['id'],str(movie),rev,'H1',notes='Tight pacing and larger flush-corner presenter revision; review edit, commercial photo reuse unverified.')
(R/'ad-system-delivery.json').write_text(json.dumps({'revision':rev,'stage':r['stage'],'automated_review_id':review,'export':export},indent=2)+'\n')
(R/'memory-delivery.md').write_text(summary+'\n');remember(st,r['id'],summary,'User dead-space and corner request; verified Resolve revision, September12,2026','observation')
print(json.dumps({'revision':rev,'stage':r['stage'],'export_id':export['id'],'movie':str(movie),'sha256':sha,'cutroom':board['url']},indent=2),flush=True)
