import pathlib,json
O=pathlib.Path(__file__).resolve().parent;ready=json.loads((O/'presenter-ready.json').read_text());end=ready['spoken_video_frames'];D=O/'deliverables';D.mkdir(exist_ok=True)
code='''local r=fu:GetResolve();assert(r);local pm=r:GetProjectManager();local p=pm:GetCurrentProject();assert(p:GetName()=='MOT-UGC-YAPPER-01 v6 20260909','Wrong project');assert(not p:IsRenderingInProgress());local staging=nil
for i=1,p:GetTimelineCount() do local t=p:GetTimelineByIndex(i);if t:GetName()=='v6 STAGING - Avatar V pending' then staging=t end;assert(t:GetName()~='v6 FINAL - ElevenLabs Avatar V','Final timeline already exists; inspect it instead of rerunning') end
assert(staging);p:SetCurrentTimeline(staging);local t=staging:DuplicateTimeline('v6 FINAL - ElevenLabs Avatar V');assert(t);p:SetCurrentTimeline(t);local old=t:GetItemListInTrack('video',1);assert(#old==1 and string.find(old[1]:GetName(),'TEMP'),'Unexpected staging V1');assert(t:DeleteClips(old,false));local mp=p:GetMediaPool();local media=mp:ImportMedia({__VIDEO__,__HOLD__});assert(media and #media==2)
local a=mp:AppendToTimeline({{mediaPoolItem=media[1],startFrame=0,endFrame=__SPOKEN__,recordFrame=0,trackIndex=1,mediaType=1}})[1];assert(a);local b=mp:AppendToTimeline({{mediaPoolItem=media[2],startFrame=0,endFrame=10145-__SPOKEN__,recordFrame=__SPOKEN__,trackIndex=1,mediaType=1}})[1];assert(b)
assert(a:GetStart()==0 and a:GetEnd()==__SPOKEN__,'Presenter range mismatch');assert(b:GetStart()==__SPOKEN__ and b:GetEnd()==10145,'End hold range mismatch');assert(t:GetEndFrame()==10145);assert(#t:GetItemListInTrack('video',2)==20);assert(#t:GetItemListInTrack('video',3)==228);assert(#t:GetItemListInTrack('audio',1)==1);t:DeleteMarkerAtFrame(0);t:SetTrackName('video',1,'HeyGen Avatar V - continuous');t:AddMarker(__SPOKEN__,'Blue','Final 3-second face hold','Actual final Avatar V frame, no product or guarantee overlay.',10145-__SPOKEN__);assert(pm:SaveProject());print('FINAL_ASSEMBLED',t:GetName(),t:GetEndFrame())
print('DRP',pm:ExportProject(p:GetName(),__DRP__));print('DRT',t:Export(__DRT__,r.EXPORT_DRT,r.EXPORT_NONE))
p:SetCurrentRenderMode(1);assert(p:SetCurrentRenderFormatAndCodec('mp4','H264'));assert(p:SetRenderSettings({TargetDir=__OUT__,CustomName='Motilli-Unbranded-VSL-v6',SelectAllFrames=true,FormatWidth=1080,FormatHeight=1920,FrameRate=30,ExportVideo=true,ExportAudio=true,AudioCodec='aac',AudioSampleRate=48000,VideoQuality=16000,NetworkOptimization=true}));local id=p:AddRenderJob();print('FINAL_RENDER_JOB',id);print('FINAL_RENDER_STARTED',p:StartRendering(id));pm:SaveProject()
'''
for k,v in {'__VIDEO__':json.dumps(ready['video']),'__HOLD__':json.dumps(ready['hold']),'__SPOKEN__':str(end),'__DRP__':json.dumps(str(D/'MOT-UGC-YAPPER-01-v6-FINAL.drp')),'__DRT__':json.dumps(str(D/'MOT-UGC-YAPPER-01-v6-FINAL.drt')),'__OUT__':json.dumps(str(D))}.items():code=code.replace(k,v)
(O/'assemble-final.lua').write_text(code);print('Final native Resolve assembly prepared')
