from pathlib import Path
import json,subprocess,shutil
b=Path(__file__).resolve().parents[1];root=next(x for x in b.parents if (x/'cutroom/board_builder.py').exists());src=root/'brands/velantra/creative/eleanor-european-travel-2026-09-11';beats=json.loads((b/'edit/beats.json').read_text());original=json.loads((src/'production/tight/aligned-scenes.json').read_text());assets=b/'storyboard/assets'
shutil.copy2(src/'production/presenter/P01-green.png',assets/'P01-retained-presenter.png');shutil.copy2(src/'production/resolve/closing-overlay.png',assets/'O01-retained-overlay.png')
subprocess.run(['ffmpeg','-v','error','-y','-i',str(b/'production/exports/Eleanor-EuropeanTravel-FourColors-Final.mp4'),'-vf','select=eq(n\\,1300)','-frames:v','1','-q:v','2',str(assets/'S07-motion-first-frame.jpg')],check=True)
lanes=[]
for reference in [True,False]:
 items=[]
 for i,z in enumerate(beats):
  desc=original[i] if reference else z
  f=(b/'edit/reference-analysis/selected-frames' if reference else b/'storyboard/final-composites')/(z['id']+'.jpg');assert f.exists()
  items.append({'t':f"{z['id']} · {z['in']/30:.3f}–{z['out']/30:.3f}s",'script':z['line'],'frame':str(f),'visual':desc['visual'],'emotion':desc['why'],'note':z['cut_cue']+' Direct background cuts. Existing voice, guide and caption timing retained.'})
 lanes.append({'label':'ORIGINAL EUROPEAN TRAVEL TIGHT — REFERENCE' if reference else 'FINAL FOUR-COLOR REVISION','source':'User-selected European Travel Tight master, 70.67 seconds' if reference else 'Finished DaVinci Resolve export · 1080×1920 · 30 fps · 70.67 seconds','beats':items})
spec={'title':'Weekender — European travel / four-color women','project':'velantra','summary':'Same European Travel Tight ad with the opening grid revised to four women carrying Weekender: Cognac top-left, Army Green top-right, Dark Chocolate bottom-left and Black bottom-right. Four aspirational outfits make the styling promise readable immediately. The exact script, Woman Over 40 Eleven v3 Natural voice at existing 1.1× speed, Avatar V guide, 76 captions, tightened pauses, city examples and final CTA are preserved.','timelines':lanes,'notes':[{'title':'OPENING COLOR ORDER','text':'Cognac / Army Green across the top. Dark Chocolate / Black across the bottom. The raised Dark Chocolate bag clears the original lower-left guide. Opening holds 0–9.5 seconds, then cuts to the existing Cognac product view.','color':'#dff2e1'},{'title':'ORIGINAL PACE PRESERVED','text':'No additional speed change: Eleven v3 Natural was already generated at 1.1×. All 28 retained audio intervals and 76 caption phrases remain intact. The final audio is byte-identical to the source; no internal quiet gaps of 0.2 seconds or longer were detected at −40 dB. The short ending hold remains.','color':'#fdf3c9'},{'title':'STYLING SEQUENCE','text':'Four-color inspiration → Cognac choice → leather and canvas detail → Paris outfit → Milan outfit and jewelry detail → London textures → wardrobe summary → between-cities payoff → shop invitation. The four opening looks inspire; Paris, Milan and London remain the three narrated city demonstrations.','color':'#f7f5ee'},{'title':'FINAL MEDIA VERIFIED','text':'All 2,120 frames decoded. All 1,835 body frames after the opening matched the exact source within normal re-encoding variation. Consecutive cut frames, the opening at full size, presenter clearance and final CTA inspected. No measured campaign performance is claimed.','color':'#dff2e1'}],'moodboard':[{'image':str(assets/'fourcolorgridselected.png'),'caption':'SELECTED CLEAN HOOK — four different women, requested color order. The final lane shows the rendered presenter and captions.'},{'image':str(assets/'P01-retained-presenter.png'),'caption':'RETAINED P01 — original blonde Avatar V guide source. Green is keyed away in the actual final composites.'},{'image':str(assets/'S07-motion-first-frame.jpg'),'caption':'LONDON MOTION START — actual first retained motion frame at 43.333 seconds, following the held London image. Milan and train motion starts appear on S05 and S09.'},{'image':str(assets/'O01-retained-overlay.png'),'caption':'RETAINED O01 — closing shop overlay, 68.300–70.667 seconds.'},{'image':str(b/'production/qa/final-cta.png'),'caption':'FINISHED END FRAME — original short hold, guide and shop graphic. No extra blank or static tail.'}]}
p=b/'storyboard/cutroom-spec.json';p.write_text(json.dumps(spec,indent=2));subprocess.run(['python3',str(root/'cutroom/board_builder.py'),str(p),'--slug','weekender-european-travel-four-colors-2026-09-13'],check=True)
