# 100-scene B-roll library: The Ingrid Top Handle Tote (Velantra)
# Each entry: (id, product, colorway, category, open_bag, scene, motion)
# scene = the middle of the keyframe prompt. motion = the Omni motion prompt body.
# Style rules: simple sentences, commas and periods only, no em dashes, no on-screen text,
# faces never in frame, one colorway per frame, 9:16.
# Colorway split: bordeaux 50, black 25, cognac 25.
# Lane guard: no office or desk scenes (Margot's lane), no airport or hotel scenes (Weekender's lane).

STILL = "Slow handheld push in toward the bag with a gentle natural sway, as if someone is holding a phone. Everything in the scene stays where it is and every detail of the bag stays exactly as in the image."
DRIFT = "Very slow handheld drift sideways across the scene with slight focus breathing. Every detail of the bag stays exactly as in the image, nothing on the bag moves or changes shape."
OVERHEAD = "Slow overhead handheld drift with a slight wobble. The contents settle naturally but the bag itself stays exactly as in the image."
WALK_AWAY = "She keeps walking away from the camera at a relaxed pace and the bag sways gently with her stride. Handheld follow with natural footstep bounce. The bag keeps its exact shape and details."
WALK_BY = "She walks past the camera at a relaxed pace and the bag swings gently at her side. Handheld with natural shake. The bag keeps its exact shape and details."
CARRY_HOLD = "She shifts her weight slightly and the bag moves with her arm in tiny natural motions. Handheld camera with a soft sway. The bag keeps its exact shape and details."
MACRO = "Extremely slow macro pan across the surface of the bag with shallow focus breathing. Nothing in the scene moves. Every detail of the bag stays exactly as in the image, the straps stay two separate straps and the hardware never changes shape."

SCENES = []

ING = "ingrid"
ing = [
# ============================================================
# A. Street and carry action (18): 001-018
("street-crosswalk-back", "bordeaux", "carry", False,
 "A photo taken from behind of a woman mid stride crossing a city crosswalk on an overcast fall morning. She wears a long camel wool coat, straight leg jeans and leather ankle boots, and carries the bag in her right hand by both top handles so it swings beside her knee. Her head is turned slightly so no face is visible. Wet patches on the asphalt and far pedestrians out of focus.",
 WALK_AWAY),
("street-crook-elbow", "bordeaux", "carry", False,
 "A chest to knee crop of a woman standing on a quiet sidewalk holding the bag in the crook of her elbow at hip height, her wrist bent under its weight. She wears an oversized cream cable knit sweater and dark trousers, no face in frame. Soft overcast daylight, a brick storefront blurred behind her.",
 CARRY_HOLD),
("street-coffee-run", "bordeaux", "carry", False,
 "A mid body crop of a woman on a fall sidewalk holding a paper coffee cup in one hand while the bag hangs from her other forearm. Camel trench coat, thin gold ring on her finger, no face in frame. Morning sun rakes across the pavement behind her.",
 CARRY_HOLD),
("street-brownstone-steps", "bordeaux", "carry", False,
 "A side view of a woman walking past old brownstone steps carrying the bag by both top handles in one hand so it swings near her knee. Long black wool coat and cream scarf, face out of frame above the shoulders. Late afternoon golden light on the stone.",
 WALK_BY),
("street-leaf-path", "black", "carry", False,
 "A photo from behind at waist height of a woman walking down a leaf covered park path, the bag hanging from her hand and brushing her coat with each step. Grey wool coat and white sneakers, fallen yellow leaves everywhere, low afternoon sun flaring slightly into the lens.",
 WALK_AWAY),
("street-two-hand-front", "bordeaux", "carry", False,
 "A front view crop from chin to knees of a woman standing on a corner holding the bag in front of her thighs with both hands on the top handles. Cream turtleneck under a camel blazer. The bag hangs with real weight, its leather creased and catching the light. Blurred crosswalk stripes beyond.",
 CARRY_HOLD),
("street-bookstore-door", "cognac", "carry", False,
 "A photo of a woman from the shoulders down pushing open the glass door of a small bookstore, the bag in the crook of her arm, a wrapped paperback in her other hand. Warm light from inside spills onto the darkening sidewalk in the early evening.",
 CARRY_HOLD),
("street-market-stall", "cognac", "carry", False,
 "A chest down photo of a woman at an outdoor farmers market stall, the bag hanging from her forearm while her free hand reaches for a bunch of eucalyptus. Crates of apples and pumpkins fill the blurred background. Soft overcast light.",
 CARRY_HOLD),
("street-phone-check", "black", "carry", False,
 "A close crop of a woman from chest to hips standing on a corner looking at her phone, the bag hanging from her forearm in front of her. Black wool coat, delicate gold bracelet, blurred taxis far beyond.",
 CARRY_HOLD),
("street-evening-lamplight", "black", "carry", False,
 "A photo of a woman from the shoulders down standing on an evening street, the bag in her hand catching the warm glow of a shop window. Silk skirt and heeled boots, street lights just turning on, shallow depth of field.",
 CARRY_HOLD),
("street-museum-steps", "bordeaux", "carry", False,
 "A photo from below of a woman coming down wide stone museum steps, the bag in one hand by both handles, her other hand holding her coat closed. Plaid wool skirt, black tights, loafers, her face cropped out by the top of the frame. Cold bright fall daylight.",
 WALK_BY),
("street-dogwalk", "cognac", "carry", False,
 "A photo from behind of a woman walking a small dog on a leash down a residential fall street, the bag hanging from her free hand. Golden hour light through bare branches, long shadows on the sidewalk.",
 WALK_AWAY),
("street-umbrella", "bordeaux", "carry", False,
 "A chest down photo of a woman under a dark umbrella on a drizzly street, the bag on her forearm held slightly forward. Small rain drops bead on the glossy creased leather and the wet asphalt reflects the grey sky.",
 CARRY_HOLD),
("street-crisp-morning", "cognac", "carry", False,
 "A low angle photo from knee height of a woman walking toward the camera on a tree lined sidewalk, cropped at the shoulders, the bag swinging by her side in her hand. Cold morning air, frost still on parked car windows.",
 WALK_BY),
("street-flower-wrap", "black", "carry", False,
 "A photo of a woman from the shoulders down outside a florist, the bag in the crook of one arm and a paper cone of white ranunculus held against her chest with the other. Buckets of flowers blur behind her in soft morning light.",
 CARRY_HOLD),
("street-cobblestone-back", "bordeaux", "carry", False,
 "A photo taken from behind of a woman walking away down a narrow cobblestone street between old stone buildings, the bag in her hand swaying with her stride. Wool coat with the collar turned up, early evening blue light with warm windows above.",
 WALK_AWAY),
("street-bus-bench", "black", "carry", False,
 "A photo of a woman sitting on a bus stop bench, cropped from the neck down, the bag standing upright on her lap with her hands resting over the top handles. Wool coat and leather gloves, morning fog softening the street behind.",
 STILL),
("street-curb-step", "bordeaux", "carry", False,
 "A front view crop from waist to ankle of a woman stepping off a curb mid stride, the bag in her hand near her knee, its brass hardware catching the light. Dark denim and chelsea boots, blurred storefronts behind.",
 WALK_BY),

# ============================================================
# B. Cafe, bakery, restaurant (12): 019-030
("cafe-bistro-chair", "bordeaux", "cafe", False,
 "A photo of the bag sitting upright on a woven cane bistro chair at a small marble cafe table. An espresso cup and a half eaten croissant sit on the table, sunglasses tossed beside them. Morning window light with real shadows across the chair.",
 STILL),
("cafe-marble-table", "cognac", "cafe", False,
 "A photo of the bag standing on a small round marble cafe table beside a flat white in a ceramic cup, a teaspoon resting on the saucer. Crumbs and a folded receipt on the marble, a rain streaked window softening the street beyond.",
 STILL),
("cafe-window-counter", "black", "cafe", False,
 "A photo of the bag sitting on a wooden window bar counter inside a cafe, an iced latte sweating beside it and a phone lying face down. Strong side light from the window blows out the highlights on the glass, street blur outside.",
 STILL),
("cafe-floor-lean", "bordeaux", "cafe", False,
 "A photo at floor level of the bag standing on worn cafe floorboards, leaning slightly against the leg of a bentwood chair. A woman's crossed ankles in loafers sit just behind it, cropped at the shin. Warm afternoon light stripes the floor.",
 STILL),
("cafe-banquette", "bordeaux", "cafe", False,
 "A photo of the bag resting on a leather banquette seat beside a woman's hip, her cream knit sleeve and hand visible resting near the handles, no face in frame. A brunch table with orange juice and toast blurs in the foreground edge.",
 STILL),
("cafe-croissant-morning", "cognac", "cafe", False,
 "A photo of the bag on a wooden cafe table next to a paper plate with a flaky croissant torn open, butter knife across it. Flakes scattered on the wood, morning sun catching the burnished leather unevenly.",
 STILL),
("cafe-outdoor-terrace", "bordeaux", "cafe", False,
 "A photo of the bag sitting on a rattan terrace chair outside a cafe, a folded newspaper tucked beside it on the seat. Empty espresso cups on the table, low fall sun and long shadows across the pavement.",
 STILL),
("cafe-bakery-counter", "cognac", "cafe", False,
 "A photo of the bag standing on a bakery pickup counter beside a folded paper pastry bag, a hand reaching for the bag handles from the side with a gold ring visible. Glass pastry case glowing warm and out of focus behind.",
 STILL),
("cafe-latte-hand", "black", "cafe", False,
 "A close photo of a woman's hands at a cafe table, one hand wrapped around a warm latte glass, the bag standing on the bench beside her thigh. Chunky knit sleeve, thin gold rings, no face in frame. Soft window light.",
 STILL),
("cafe-book-afternoon", "bordeaux", "cafe", False,
 "A photo of the bag on a small wooden table beside an open novel lying face down and a pair of reading glasses. A half finished cappuccino with dried foam rings inside the cup. Quiet late afternoon light through a dusty window.",
 STILL),
("cafe-wine-bar-dusk", "black", "cafe", False,
 "A photo of the bag standing on a dark wood wine bar counter beside two glasses of red wine, a lit candle flickering just behind it. Warm dim evening light, deep shadows, the glossy black leather catching the candle flame.",
 STILL),
("cafe-diner-booth", "cognac", "cafe", False,
 "A photo of the bag sitting on a worn red vinyl diner booth beside a laminated menu, morning sun cutting across the table and lighting dust in the air. Chrome napkin holder and a ketchup bottle blurred at the frame edge.",
 STILL),

# ============================================================
# C. Car (8): 031-038
("car-passenger-seat", "bordeaux", "car", False,
 "A photo of the bag standing upright on a car passenger seat, the seat belt hanging behind it and the door pillar visible. Golden hour side light through the glass rakes across the creased leather. Dust in the seams of the leather seat.",
 STILL),
("car-console-latte", "cognac", "car", False,
 "A photo of the bag on the passenger seat of a car with an iced latte in the center console cup holder beside it, condensation on the plastic cup. Overcast daylight through the windshield, a parking lot softly blurred beyond.",
 STILL),
("car-trunk-market", "bordeaux", "car", False,
 "A photo of the bag standing in an open car trunk beside a paper grocery sack with leeks and a baguette sticking out. Late afternoon light from behind, a quiet residential street blurred past the trunk lid.",
 STILL),
("car-lap-passenger", "black", "car", False,
 "A photo of the bag standing on a woman's lap in the passenger seat, her hands resting on the top handles, cropped at the chest. Wool skirt and tights, soft grey daylight through the side window, rain drops on the glass.",
 STILL),
("car-door-open", "bordeaux", "car", False,
 "A photo of the bag on the driver seat of a parked car with the door open, keys with a leather fob tossed on the seat beside it. A brick driveway and hedge soft in the background, low morning sun.",
 STILL),
("car-backseat-sunbeam", "cognac", "car", False,
 "A photo of the bag on the back seat of a car, a wool scarf spilling out from under it onto the tan leather seat. A hard beam of afternoon sun cuts across the bag leaving the rest of the cabin in shadow.",
 DRIFT),
("car-rain-windshield", "black", "car", False,
 "A photo of the bag on the passenger seat of a parked car during rain, the windshield behind it covered in beaded drops, grey light flattening the cabin. A folded umbrella drips on the rubber floor mat.",
 STILL),
("car-keys-seat", "bordeaux", "car", False,
 "A close photo of the bag on a car seat with a set of house keys and a phone tossed beside it, the phone screen dark. The stitching and brass clasp plates of the bag catch the soft light from the window.",
 STILL),

# ============================================================
# D. Home: counter, table, entryway (14): 039-052
("home-kitchen-counter", "bordeaux", "home", False,
 "A photo of the bag standing on a white marble kitchen counter in morning light, a French press and two ceramic mugs beside it, steam rising faintly. Crumbs on a wooden cutting board at the frame edge, window light blowing out softly behind.",
 STILL),
("home-island-flowers", "cognac", "home", False,
 "A photo of the bag on a kitchen island next to a bunch of grocery store tulips still in their paper sleeve and a set of keys. Afternoon light from a side window, a dish towel crumpled nearby.",
 STILL),
("home-dining-table", "black", "home", False,
 "A photo of the bag standing on a worn oak dining table, a linen runner bunched beneath it and a low bowl of pears further down the table. Soft north light from tall windows, the glossy black leather holding deep reflections.",
 STILL),
("home-entry-console", "bordeaux", "home", False,
 "A photo of the bag on a narrow entryway console table beside a ceramic bowl of keys and a stack of unopened mail. A coat sleeve hangs into the frame edge from a hook above. Warm lamp light mixing with cool daylight from the door.",
 STILL),
("home-entry-floor", "cognac", "home", False,
 "A photo of the bag standing on herringbone wood floor in an entryway, leaning slightly against the wall below a row of coat hooks with a trench coat and a canvas jacket. Leather loafers kicked off beside it. Daylight from a front door window.",
 STILL),
("home-bed-bench", "bordeaux", "home", False,
 "A photo of the bag sitting on a linen upholstered bench at the foot of a bed, a folded grey blanket beside it and an unmade duvet behind. Morning light through sheer curtains, dust motes visible in the beam.",
 STILL),
("home-armchair", "bordeaux", "home", False,
 "A photo of the bag resting on the seat of a worn leather reading armchair, a wool throw hanging over the armrest and a paperback on the side table. Low warm lamp light in the evening, shadows deep in the corners.",
 STILL),
("home-window-sill", "black", "home", False,
 "A photo of the bag standing on a deep painted window sill, hard raking afternoon light from the side exaggerating every crease in the black leather. An old radiator below, street soft through the glass behind.",
 DRIFT),
("home-bathroom-vanity", "black", "home", False,
 "A photo of the bag standing on a marble bathroom vanity beside a glass perfume bottle and a gold watch laid flat. Soft light from a frosted window, water spots on the mirror edge just visible at the frame side.",
 STILL),
("home-bookshelf-corner", "bordeaux", "home", False,
 "A photo of the bag standing on a wool rug in the corner of a living room beside a stack of hardcover books and a floor lamp base. Late golden light stripes the rug through window blinds.",
 STILL),
("home-radiator-window", "cognac", "home", False,
 "A photo of the bag on wooden floorboards under a tall window beside an old cast iron radiator, hard afternoon light throwing the window frame shadow across the floor and over the bag.",
 STILL),
("home-mirror-check", "bordeaux", "home", False,
 "A photo of a woman reflected in a full length bedroom mirror from the neck down, the bag in the crook of her elbow, her phone raised in her other hand hiding where her face would be. An unmade bed and clothes on a chair blur in the reflection behind her.",
 CARRY_HOLD),
("home-staircase-newel", "black", "home", False,
 "A photo of the bag hanging by both top handles from the newel post of a wooden staircase, a wool coat draped over the banister above it. Evening lamp light from the hallway, the stair treads worn pale in the middle.",
 STILL),
("home-kitchen-table-paper", "cognac", "home", False,
 "A photo of the bag standing on a small kitchen table beside a folded weekend newspaper and a pair of tortoiseshell glasses, a mug of black coffee half finished. Mid morning light, toast crumbs on a plate at the frame edge.",
 STILL),

# ============================================================
# E. Open bag, overhead and interior (8): 053-060
("open-overhead-bed", "bordeaux", "open", True,
 "An overhead photo looking down into the bag standing open on a wrinkled white duvet. Inside, a leather wallet, a phone, a small pouch and keys sit against the natural tan suede interior. Soft window light from one side, the duvet creased and lived in.",
 OVERHEAD),
("open-overhead-counter", "cognac", "open", True,
 "An overhead photo looking down into the bag standing open on a kitchen counter, a glasses case and a folded silk scarf nested inside against the tan suede interior. A chopping board and kettle blurred at the frame edges, morning light.",
 OVERHEAD),
("open-carseat-45", "black", "open", True,
 "A photo at a high angle looking into the bag standing open on a car passenger seat, a water bottle and a paperback visible inside against the tan suede interior. Seat belt buckle beside it, soft daylight through the windshield.",
 STILL),
("open-lap-cafe", "bordeaux", "open", True,
 "A photo of the bag standing open on a woman's lap at a cafe table, her hand reaching inside for something, cropped at the chest, no face in frame. The tan suede interior catches the window light. A coffee cup blurred in the foreground.",
 STILL),
("open-entry-table", "bordeaux", "open", True,
 "A photo of the bag standing open on an entryway table, a wool scarf half spilling out of the mouth and sunglasses hooked over the edge. The tan suede interior visible in shadow. A front door with frosted glass glows behind.",
 STILL),
("open-sofa-corner", "cognac", "open", True,
 "A photo of the bag standing open in the corner of a linen sofa, a cardigan sleeve trailing out of it onto the cushion. Warm evening lamp light, a knit blanket bunched beside it.",
 STILL),
("open-bed-45", "black", "open", True,
 "A photo at a 45 degree angle looking into the bag standing open on a made bed, a notebook and a small leather pouch inside against the tan suede interior. Sheer curtain light softening everything, a folded sweater beside the bag.",
 STILL),
("open-floor-rug", "bordeaux", "open", True,
 "An overhead photo of the bag standing open on a woven wool rug, a rolled magazine and keys inside it, one belt strap fallen across the floor. Afternoon sun through a window lays a bright parallelogram across the rug beside it.",
 OVERHEAD),

# ============================================================
# F. Packing action (12): 061-072
("pack-sweater", "bordeaux", "packing", True,
 "A photo of a woman's hands lowering a folded cream sweater into the bag standing open on a bed. Thin gold ring, natural skin texture, cropped at the forearms. The tan suede interior visible past the sweater, morning light from a window behind.",
 "Her hands lower the folded sweater into the open bag in one slow natural motion and press it down gently. Handheld with a soft sway. The bag stays standing open and keeps its exact shape, the two straps and the brass hardware stay exactly as in the image."),
("pack-book", "cognac", "packing", True,
 "A photo of a woman's hand sliding a hardcover novel into the bag standing open on a kitchen table, the book half inside the mouth. A coffee mug and folded glasses beside the bag, soft mid morning light.",
 "Her hand slides the book fully into the open bag in one smooth natural motion and lets go. Handheld with a gentle sway. The bag stays standing open and keeps its exact shape, the two straps and the brass hardware stay exactly as in the image."),
("pack-waterbottle", "black", "packing", True,
 "A photo of a woman's hand lowering a brushed steel water bottle into the bag standing open on a counter, cropped at the wrist. The tan suede interior in shadow inside the mouth, cool daylight from the side.",
 "Her hand lowers the bottle into the open bag in one slow natural motion and releases it. Handheld with a soft sway. The bag stays standing open and keeps its exact shape, the two straps and the brass hardware stay exactly as in the image."),
("pack-pouch", "bordeaux", "packing", True,
 "A photo of a woman's hands placing a small taupe leather pouch into the bag standing open on a linen bench at the foot of a bed. Natural skin texture, a thin gold bracelet. Soft window light, the duvet blurred behind.",
 "Her hands place the pouch into the open bag in one slow natural motion and settle it inside. Handheld with a soft sway. The bag stays standing open and keeps its exact shape, the two straps and the brass hardware stay exactly as in the image."),
("pack-scarf", "cognac", "packing", True,
 "A photo of a woman's hand feeding a cream silk scarf into the bag standing open on a dining table, the scarf half draped over the mouth mid motion. Afternoon light catching the burnished leather.",
 "Her hand tucks the scarf down into the open bag in one soft natural motion. Handheld with a gentle sway. The bag stays standing open and keeps its exact shape, the two straps and the brass hardware stay exactly as in the image."),
("pack-keys-drop", "bordeaux", "packing", True,
 "A photo of a woman's hand holding a set of keys on a leather fob just above the open mouth of the bag standing on an entry console, about to drop them in. Cropped at the wrist, warm lamp light and cool door light mixing.",
 "Her hand drops the keys into the open bag and they disappear inside. Handheld with a soft sway. The bag stays standing open and keeps its exact shape, the two straps and the brass hardware stay exactly as in the image."),
("pack-glasses-case", "black", "packing", True,
 "A photo of a woman's hand lowering a hard tortoiseshell glasses case into the bag standing open on a marble counter. Thin gold rings, natural knuckle creases. Bright window light blowing out behind, the glossy black leather holding reflections.",
 "Her hand lowers the glasses case into the open bag in one slow natural motion and lets go. Handheld with a soft sway. The bag stays standing open and keeps its exact shape, the two straps and the brass hardware stay exactly as in the image."),
("pack-baguette", "cognac", "packing", True,
 "A photo of a woman's hands sliding a paper wrapped baguette diagonally into the bag standing open on a kitchen counter, market vegetables scattered nearby. Warm late morning light, flour dust on the counter.",
 "Her hands settle the baguette into the open bag in one smooth natural motion. Handheld with a gentle sway. The bag stays standing open and keeps its exact shape, the two straps and the brass hardware stay exactly as in the image."),
("pack-umbrella", "bordeaux", "packing", True,
 "A photo of a woman's hand sliding a compact navy umbrella into the bag standing open on an entry table, rain streaking the window beside the door. Grey daylight, a wet trench coat on a hook at the frame edge.",
 "Her hand slides the umbrella down into the open bag in one smooth natural motion. Handheld with a soft sway. The bag stays standing open and keeps its exact shape, the two straps and the brass hardware stay exactly as in the image."),
("pack-cardigan-out", "bordeaux", "packing", True,
 "A photo of a woman's hand pulling a folded oat cardigan up out of the bag standing open on a sofa cushion, the knit halfway out of the mouth. Evening lamp light, a blanket bunched in the corner of the frame.",
 "Her hand lifts the cardigan up and out of the open bag in one slow natural motion. Handheld with a soft sway. The bag stays standing open and keeps its exact shape, the two straps and the brass hardware stay exactly as in the image."),
("pack-wallet", "black", "packing", True,
 "A photo of a woman's hand sliding a slim black leather wallet into the bag standing open on a bed, cropped at the forearm, a coat laid out beside it ready to wear. Cool morning light through sheer curtains.",
 "Her hand slides the wallet into the open bag and releases it. Handheld with a gentle sway. The bag stays standing open and keeps its exact shape, the two straps and the brass hardware stay exactly as in the image."),
("pack-tissue-parcel", "cognac", "packing", True,
 "A photo of a woman's hands lowering a small parcel wrapped in white tissue paper into the bag standing open on a boutique counter, string tied around the parcel. Soft shop light, a wooden counter worn smooth.",
 "Her hands lower the wrapped parcel into the open bag in one careful natural motion. Handheld with a soft sway. The bag stays standing open and keeps its exact shape, the two straps and the brass hardware stay exactly as in the image."),

# ============================================================
# G. What fits, flat lays (4): 073-076
("flatlay-duvet", "bordeaux", "flatlay", False,
 "An overhead photo on a wrinkled white duvet, the bag standing closed at the top of the frame and its everyday contents laid out loosely below it, a leather wallet, a phone, wireless earbuds, keys on a fob, a lip balm, a small planner and a pair of sunglasses. Soft window light from one side, the duvet creased and real.",
 OVERHEAD),
("flatlay-rug", "cognac", "flatlay", False,
 "An overhead photo on a flatwoven wool rug, the bag standing closed at the top of the frame and its contents in a loose grid below, a hardcover book, a silk scarf, a glasses case, hand cream, keys and a small pouch. Afternoon window light angling across the rug weave.",
 OVERHEAD),
("flatlay-linen", "black", "flatlay", False,
 "An overhead photo on washed oatmeal linen sheets, the bag standing closed at the top of the frame and its contents below, a slim wallet, gold jewelry in a small dish, a phone face down, a knit beanie and a paperback. Low warm light stretching shadows across the linen.",
 OVERHEAD),
("flatlay-fall-edit", "bordeaux", "flatlay", False,
 "An overhead photo on pale wood floorboards, the bag standing closed at the top of the frame with a camel scarf folded beside it and below them a novel, tortoiseshell sunglasses, keys, a lip balm and a takeaway coffee cup with a faint ring stain under it. Overcast window light, one floorboard nail catching the light.",
 OVERHEAD),

# ============================================================
# H. Macro details (14): 077-090
("macro-turnlock", "bordeaux", "macro", False,
 "An extreme close photo of the small brass turn lock at the top center of the bag front, the surrounding dark leather heavily creased and catching a thin line of window light. Very shallow focus, the rest of the bag falling away soft.",
 MACRO),
("macro-clasp-plate", "bordeaux", "macro", False,
 "An extreme close photo of one angled brushed gold clasp plate at the end of the light tan belt strap, the strap passing through its raised brass staple loop just above. Every pore and crease of the two leathers visible, shallow focus, soft daylight.",
 MACRO),
("macro-handle-root", "bordeaux", "macro", False,
 "An extreme close photo of one rolled espresso leather handle where it passes down through the shaped cutout in the front panel of the bag, the hand stitching along the panel edge visible. Raking side light, very shallow focus.",
 MACRO),
("macro-stitch-topedge", "cognac", "macro", False,
 "An extreme close photo of the hand stitched seam running along the curved top edge of the bag, the thick thread slightly uneven the way hand stitching is, the burnished whiskey leather glowing in low sun. Shallow focus.",
 MACRO),
("macro-patina-crease", "bordeaux", "macro", False,
 "An extreme close photo of the front face of the bag where the antiqued leather creases and folds, hard raking light from one side making the glossy high spots flare and the folds go dark. Nothing else in frame, shallow focus.",
 MACRO),
("macro-corner-foot", "cognac", "macro", False,
 "An extreme close photo at floor level of one reinforced corner cap of the bag and the small metal foot beneath it, sitting on worn oak floorboards with dust in the gaps. Window light from behind, shallow focus.",
 MACRO),
("macro-piping-gusset", "bordeaux", "macro", False,
 "An extreme close photo of the light tan edge piping running down the side gusset of the bag, the dark creased body leather on either side of the clean piping line. Soft window light, very shallow focus.",
 MACRO),
("macro-belt-staple", "black", "macro", False,
 "An extreme close photo of one black belt strap where it passes through its raised brass staple loop on the bag front, the brass softly worn at the edges. The glossy black leather creased around it, shallow focus, low warm light.",
 MACRO),
("macro-grain-raking", "black", "macro", False,
 "An extreme close photo of the black leather surface of the bag in hard raking window light, the creases and grain reading like a landscape, highlights blown where the gloss catches. Nothing else in frame.",
 MACRO),
("macro-rivet-corner", "cognac", "macro", False,
 "An extreme close photo of the small round rivet at the top corner of the bag front panel, the stitching line running away from it out of focus. Burnished leather glowing warm, shallow depth of field.",
 MACRO),
("macro-hand-handle", "bordeaux", "macro", False,
 "A close photo of a woman's hand resting on the two rolled handles of the bag, a thin gold ring on her finger, natural skin texture with visible pores and fine lines. The dark creased leather fills the rest of the frame, soft daylight.",
 MACRO),
("macro-interior-suede", "bordeaux", "macro", True,
 "A close photo looking into the open mouth of the bag, the natural tan suede interior wall catching a wedge of window light while the rest falls into shadow. The stitched top edge in the foreground slightly out of focus.",
 MACRO),
("macro-rain-beads", "black", "macro", False,
 "An extreme close photo of rain drops beaded on the glossy black creased leather of the bag, each drop holding a tiny window reflection. Grey soft daylight, very shallow focus.",
 MACRO),
("macro-strap-fingers", "cognac", "macro", False,
 "A close photo of a woman's fingers lifting the end of one belt strap away from the bag front, the brushed gold clasp plate catching the light, natural skin texture and a fine gold bracelet. Shallow focus, soft afternoon light.",
 MACRO),

# ============================================================
# I. Set downs (10): 091-100
("setdown-park-steps", "bordeaux", "setdown", False,
 "A photo of the bag standing on wide stone park steps among scattered fallen leaves, a takeaway coffee cup set beside it. Low golden afternoon light from the side, long shadows down the steps.",
 STILL),
("setdown-wood-bench", "cognac", "setdown", False,
 "A photo of the bag sitting on a weathered wooden park bench, a folded newspaper and a pair of leather gloves beside it. Bare branches soft in the background, cold bright morning light.",
 STILL),
("setdown-coat-hook", "black", "setdown", False,
 "A photo of the bag hanging by both top handles from a brass wall hook in a hallway, a wool coat on the next hook brushing against it. Warm evening light from a doorway, the wall paint scuffed near the skirting.",
 STILL),
("setdown-restaurant-floor", "bordeaux", "setdown", False,
 "A photo at floor level of the bag standing on dark restaurant floorboards beside a chair leg, the hem of a silk dress and a heeled shoe just behind it. Candlelight from the tables above throwing soft moving shadows.",
 STILL),
("setdown-picnic-blanket", "cognac", "setdown", False,
 "A photo of the bag standing on a striped wool picnic blanket on park grass, a thermos and two enamel cups beside it, a paperback face down. Hazy late afternoon sun, leaves drifting at the frame edge.",
 STILL),
("setdown-doorstep", "bordeaux", "setdown", False,
 "A photo of the bag standing on a tiled front doorstep beside a pair of leather boots, keys hanging in the lock of the painted front door above. Cool morning light, a milk bottle at the frame edge.",
 STILL),
("setdown-chair-back", "black", "setdown", False,
 "A photo of the bag hanging by its handles over the back of a bentwood cafe chair, a blazer draped beneath it. The table beyond holds an empty wine glass and a folded bill tray. Warm evening interior light.",
 STILL),
("setdown-gallery-bench", "bordeaux", "setdown", False,
 "A photo of the bag sitting on a long oak gallery bench in a quiet museum room, a folded exhibition leaflet beside it. Even grey skylight from above, parquet floor stretching away out of focus.",
 STILL),
("setdown-stoop-pumpkins", "cognac", "setdown", False,
 "A photo of the bag standing on a brick stoop beside two small pumpkins and a pot of chrysanthemums, the front door ajar behind. Warm low fall sun raking across the brick.",
 STILL),
("setdown-barstool", "black", "setdown", False,
 "A photo of the bag standing on a leather topped bar stool at a dim wine bar, brass foot rail catching the light below. Blurred bottles glowing behind the bar, a candle flame at the frame edge.",
 STILL),
]

# Category number ranges: 001-018 carry, 019-030 cafe, 031-038 car, 039-052 home,
# 053-060 open, 061-072 packing, 073-076 flatlay, 077-090 macro, 091-100 setdown.
for i, (slug, cw, cat, open_bag, scene, motion) in enumerate(ing, 1):
    SCENES.append((f"ING-{i:03d}-{slug}", ING, cw, cat, open_bag, scene, motion))

assert len(SCENES) == 100, len(SCENES)
_cw = {}
for s in SCENES:
    _cw[s[2]] = _cw.get(s[2], 0) + 1
# bordeaux 50, black 25, cognac 25
