local pm=r:GetProjectManager();local p=pm:GetCurrentProject()
assert(p:GetName()=="VEL_Weekender_EuropeanTravel_FourColors_20260913")
assert(p:GetCurrentTimeline():GetName()=="Eleanor-EuropeanTravel-FourColors")
assert(not p:IsRenderingInProgress())
assert(p:SetCurrentRenderFormatAndCodec("mp4","H264"))
assert(p:SetCurrentRenderMode(1))
assert(p:SetRenderSettings({SelectAllFrames=true,TargetDir=[=[/Users/brooksorradre2/Documents/marketing brain/brands/velantra/products/weekender/concepts/2026-09-13-european-travel-four-colors/production/exports]=],CustomName="Eleanor-EuropeanTravel-FourColors-Final",ExportVideo=true,ExportAudio=true,FormatWidth=1080,FormatHeight=1920,FrameRate=30,VideoQuality=16000,AudioCodec="aac",AudioSampleRate=48000,NetworkOptimization=true}))
local id=p:AddRenderJob();assert(id,"No job")
assert(pm:SaveProject())
local started=p:StartRendering({id})
return {job=id,started=started,project=p:GetName(),timeline=p:GetCurrentTimeline():GetName(),status=p:GetRenderJobStatus(id)}
