local ads={{[ [=[name]=] ]=[=[VEL-OM-H1-A3-R2]=],[ [=[original_id]=] ]=[=[VEL-OM-H1-A3]=],[ [=[hook_id]=] ]=[=[H1]=],[ [=[duration_frames]=] ]=1539,[ [=[otio]=] ]=[=[/Users/brooksorradre2/Documents/marketing brain/brands/velantra/creative/old-money-look-2026-09-10/production/revision-2/resolve/VEL-OM-H1-A3-R2.otio]=],[ [=[visual_clips]=] ]=15,[ [=[audio_clips]=] ]=11},{[ [=[name]=] ]=[=[VEL-OM-H2-A1-R2]=],[ [=[original_id]=] ]=[=[VEL-OM-H2-A1]=],[ [=[hook_id]=] ]=[=[H2]=],[ [=[duration_frames]=] ]=1644,[ [=[otio]=] ]=[=[/Users/brooksorradre2/Documents/marketing brain/brands/velantra/creative/old-money-look-2026-09-10/production/revision-2/resolve/VEL-OM-H2-A1-R2.otio]=],[ [=[visual_clips]=] ]=15,[ [=[audio_clips]=] ]=10},{[ [=[name]=] ]=[=[VEL-OM-H2-A2-R2]=],[ [=[original_id]=] ]=[=[VEL-OM-H2-A2]=],[ [=[hook_id]=] ]=[=[H2]=],[ [=[duration_frames]=] ]=1644,[ [=[otio]=] ]=[=[/Users/brooksorradre2/Documents/marketing brain/brands/velantra/creative/old-money-look-2026-09-10/production/revision-2/resolve/VEL-OM-H2-A2-R2.otio]=],[ [=[visual_clips]=] ]=15,[ [=[audio_clips]=] ]=10},{[ [=[name]=] ]=[=[VEL-OM-H2-A3-R2]=],[ [=[original_id]=] ]=[=[VEL-OM-H2-A3]=],[ [=[hook_id]=] ]=[=[H2]=],[ [=[duration_frames]=] ]=1644,[ [=[otio]=] ]=[=[/Users/brooksorradre2/Documents/marketing brain/brands/velantra/creative/old-money-look-2026-09-10/production/revision-2/resolve/VEL-OM-H2-A3-R2.otio]=],[ [=[visual_clips]=] ]=15,[ [=[audio_clips]=] ]=10},{[ [=[name]=] ]=[=[VEL-OM-H3-A1-R2]=],[ [=[original_id]=] ]=[=[VEL-OM-H3-A1]=],[ [=[hook_id]=] ]=[=[H3]=],[ [=[duration_frames]=] ]=1551,[ [=[otio]=] ]=[=[/Users/brooksorradre2/Documents/marketing brain/brands/velantra/creative/old-money-look-2026-09-10/production/revision-2/resolve/VEL-OM-H3-A1-R2.otio]=],[ [=[visual_clips]=] ]=15,[ [=[audio_clips]=] ]=14},{[ [=[name]=] ]=[=[VEL-OM-H3-A2-R2]=],[ [=[original_id]=] ]=[=[VEL-OM-H3-A2]=],[ [=[hook_id]=] ]=[=[H3]=],[ [=[duration_frames]=] ]=1551,[ [=[otio]=] ]=[=[/Users/brooksorradre2/Documents/marketing brain/brands/velantra/creative/old-money-look-2026-09-10/production/revision-2/resolve/VEL-OM-H3-A2-R2.otio]=],[ [=[visual_clips]=] ]=15,[ [=[audio_clips]=] ]=14},{[ [=[name]=] ]=[=[VEL-OM-H3-A3-R2]=],[ [=[original_id]=] ]=[=[VEL-OM-H3-A3]=],[ [=[hook_id]=] ]=[=[H3]=],[ [=[duration_frames]=] ]=1551,[ [=[otio]=] ]=[=[/Users/brooksorradre2/Documents/marketing brain/brands/velantra/creative/old-money-look-2026-09-10/production/revision-2/resolve/VEL-OM-H3-A3-R2.otio]=],[ [=[visual_clips]=] ]=15,[ [=[audio_clips]=] ]=14}}
local pm=r:GetProjectManager() local current=pm:GetCurrentProject() if current then assert(not current:IsRenderingInProgress()) if current:GetName()~="Untitled Project" then assert(pm:SaveProject()) end end
local name="VEL_Eleanor_OldMoney_RawPhone_R2_2026-09-11" local p=pm:LoadProject(name) assert(p and p:GetName()==name,"Load failed") assert(p:GetTimelineCount()==9,"Saved nine timelines missing") local jobs={} local result={}
for _,ad in ipairs(ads) do
 local t=nil for i=1,p:GetTimelineCount() do local candidate=p:GetTimelineByIndex(i) if candidate:GetName()==ad.name then t=candidate end end assert(t,"Missing timeline") p:SetCurrentTimeline(t)
 local v=t:GetItemListInTrack("video",1) assert(#v==15) assert(v[4]:GetMediaPoolItem():GetClipProperty("File Path"):match("bodytwocorrected.png$"),"Wrong travel source")
 assert(p:SetCurrentRenderFormatAndCodec("mp4","H264")) assert(p:SetCurrentRenderMode(1))
 assert(p:SetRenderSettings({SelectAllFrames=true,TargetDir=[=[/Users/brooksorradre2/Documents/marketing brain/brands/velantra/creative/old-money-look-2026-09-10/production/revision-2/exports]=],CustomName=ad.name,ExportVideo=true,ExportAudio=true,FormatWidth=1080,FormatHeight=1920,FrameRate=30,VideoQuality=6000,AudioCodec="aac",AudioSampleRate=48000,NetworkOptimization=true})) local id=p:AddRenderJob() assert(id) jobs[#jobs+1]=id;result[#result+1]={name=ad.name,job=id} assert(pm:SaveProject())
end
assert(pm:ExportProject(name,[=[/Users/brooksorradre2/Documents/marketing brain/brands/velantra/creative/old-money-look-2026-09-10/production/revision-2/exports/Eleanor-RawPhone-R2.drp]=]),"Final project export failed") return {project=name,project_export=true,jobs=jobs,timelines=result,started=p:StartRendering(jobs)}