from voice_v3 import O,key,save
import subprocess,json,numpy as np,httpx,base64
source=O/'narration-tight-resolve-smooth.mov';probe=json.loads(subprocess.check_output(['ffprobe','-v','error','-show_streams','-show_format','-of','json',str(source)]));save('resolve-voice-probe.json',probe);print([(s['codec_type'],s.get('codec_name'),s.get('duration')) for s in probe['streams']],flush=True)
# Audio conversion/mixing only: all speech cuts were made in Resolve.
cmd=['ffmpeg','-hide_banner','-i',str(source),'-ac','1','-af','loudnorm=I=-14:TP=-2:LRA=11:print_format=json','-f','null','-'];r=subprocess.run(cmd,capture_output=True,text=True);j=json.JSONDecoder().raw_decode(r.stderr[r.stderr.rfind('{'):])[0];save('voice-loudness-before.json',j)
af=f"loudnorm=I=-14:TP=-2:LRA=11:measured_I={j['input_i']}:measured_TP={j['input_tp']}:measured_LRA={j['input_lra']}:measured_thresh={j['input_thresh']}:offset={j['target_offset']}:linear=true:print_format=json"
r=subprocess.run(['ffmpeg','-hide_banner','-y','-i',str(source),'-ac','1','-af',af,'-ar','48000','-c:a','pcm_s24le',str(O/'narration-mix.wav')],capture_output=True,text=True,check=True);save('voice-loudness-normalized.json',json.JSONDecoder().raw_decode(r.stderr[r.stderr.rfind('{'):])[0])
subprocess.run(['ffmpeg','-v','error','-y','-i',str(O/'narration-mix.wav'),'-c:a','libmp3lame','-b:a','192k',str(O/'narration.mp3')],check=True)
prompt='Review the actual supplied audio as a neutral audio engineer. Describe only audible technical defects with precise timestamps, or report none if clean. Do not infer defects from editing methods. Check speech continuity, complete words, sound quality, naturalness, pauses, start and finish. Return JSON {verdict,issues,voice_consistency,ending}. Reference script: '+(O/'narration-exact.txt').read_text()
r=httpx.post('https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent',headers={'x-goog-api-key':key('GEMINI_API_KEY')},json={'contents':[{'parts':[{'inline_data':{'mime_type':'audio/mpeg','data':base64.b64encode((O/'narration.mp3').read_bytes()).decode()}},{'text':prompt}]}],'generationConfig':{'temperature':0.1,'responseMimeType':'application/json'}},timeout=300);r.raise_for_status();save('smooth-master-audio-qa.json',r.json());print(r.json()['candidates'][0]['content']['parts'][0]['text'],flush=True)
