local r=fu:GetResolve()
local pm=r:GetProjectManager()
local name="Motilli Podcast DVHp v5 20260909"
local p=pm:CreateProject(name)
assert(p,"Project creation failed")
p:SetSetting("timelineFrameRate","30")
p:SetSetting("timelineResolutionWidth","1080")
p:SetSetting("timelineResolutionHeight","1920")
local t=p:GetMediaPool():CreateEmptyTimeline("Podcast v5 Assembly")
assert(t,"Timeline creation failed")
pm:SaveProject()
local f=assert(io.open("/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/podcast-DVHp-2FDHAJ/production/v5/resolve-connection.txt","w"))
f:write(r:GetVersionString(),"\n",p:GetName(),"\n",t:GetName(),"\n",t:GetSetting("timelineFrameRate"))
f:close()
print("MOTILLI_ISOLATED_PROJECT_CREATED")
