local r=fu:GetResolve();local pm=r:GetProjectManager();local p=pm:GetCurrentProject();local original=nil;for i=1,p:GetTimelineCount() do local candidate=p:GetTimelineByIndex(i);if candidate:GetName()=="Motilli Podcast v5 Final 03" then original=candidate end end;assert(original);p:SetCurrentTimeline(original);local tl=original:DuplicateTimeline("Motilli Podcast v5 Final 04");assert(tl);p:SetCurrentTimeline(tl);local mp=p:GetMediaPool()
local changes={{["name"]="Split continuation Split 2 host listening",["path"]="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/podcast-DVHp-2FDHAJ/production/v5/normalized/host-listening-30fps.mp4",["start"]=829,["end"]=832,["source"]=34,["track"]=2,["kind"]="video",["properties"]={["CropTop"]=320,["CropBottom"]=640,["Tilt"]=320}},{["name"]="Split continuation Split 2 guest speaking",["path"]="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/podcast-DVHp-2FDHAJ/production/v5/normalized/guest-30fps.mp4",["start"]=829,["end"]=832,["source"]=639,["track"]=3,["kind"]="video",["properties"]={["CropTop"]=220,["CropBottom"]=740,["Tilt"]=-740}},{["name"]="Split continuation Split 3 host listening",["path"]="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/podcast-DVHp-2FDHAJ/production/v5/normalized/host-listening-30fps.mp4",["start"]=1140,["end"]=1147,["source"]=203,["track"]=2,["kind"]="video",["properties"]={["CropTop"]=320,["CropBottom"]=640,["Tilt"]=320}},{["name"]="Split continuation Split 3 guest speaking",["path"]="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/podcast-DVHp-2FDHAJ/production/v5/normalized/guest-30fps.mp4",["start"]=1140,["end"]=1147,["source"]=950,["track"]=3,["kind"]="video",["properties"]={["CropTop"]=220,["CropBottom"]=740,["Tilt"]=-740}}}
for _,row in ipairs(changes) do
 local media=mp:ImportMedia({row.path})[1]
 local v=mp:AppendToTimeline({{mediaPoolItem=media,startFrame=row.source,endFrame=row.source+row["end"]-row.start,recordFrame=row.start,trackIndex=row.track,mediaType=1}})[1]
 assert(v and v:GetStart()==row.start and v:GetEnd()==row["end"]);assert(v:SetProperty(row.properties))
end
assert(tl:GetEndFrame()==5917);print("FIXED_SPLIT_HANDLES",#changes,tl:GetName());pm:SaveProject()
p:SetCurrentRenderMode(1);p:SetCurrentRenderFormatAndCodec("mp4","H264");p:SetRenderSettings({TargetDir="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/podcast-DVHp-2FDHAJ/production/v5/deliverables",CustomName="Motilli-Podcast-Final",SelectAllFrames=true,FormatWidth=1080,FormatHeight=1920,FrameRate=30,ExportVideo=true,ExportAudio=true,VideoQuality=14000,AudioCodec="aac",AudioSampleRate=48000});local id=p:AddRenderJob();print("FINAL04_JOB",id,p:StartRendering(id))
