def esc(s):return html.escape(s)
def data(path):
 p=Path(path);return 'data:image/jpeg;base64,'+base64.b64encode(p.read_bytes()).decode()
css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f0eee7;color:#24352d;font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{padding:50px max(24px,calc((100vw - 1320px)/2));background:#183f32;color:#fff}header p{max-width:900px;color:#d7e4da}h1{font-size:clamp(30px,5vw,52px);line-height:1.1;margin:12px 0}h2{font-size:28px;margin:12px 0}.eyebrow{text-transform:uppercase;letter-spacing:2px;font-size:12px}.pills{display:flex;gap:8px;flex-wrap:wrap}.pills span{border:1px solid #6d9282;border-radius:20px;padding:5px 12px;font-size:13px}nav{position:sticky;top:0;background:#fffef9;z-index:3;display:flex;gap:8px;overflow:auto;padding:12px 20px;border-bottom:1px solid #d8ddcf}nav a{white-space:nowrap;text-decoration:none;color:#244c3a;padding:6px 12px;background:#e7edde;border-radius:7px}main{max-width:1360px;margin:auto;padding:26px 20px}section{scroll-margin-top:85px;margin-bottom:46px}.intro{max-width:930px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.card{background:#fffef9;border:1px solid #d9ddcf;border-radius:12px;overflow:hidden}.bar{display:flex;justify-content:space-between;gap:10px;padding:12px 16px;background:#e3eadc;font-weight:700}.body{display:grid;grid-template-columns:155px 1fr;gap:16px;padding:16px}.frame img{display:block;width:100%;height:auto;border-radius:6px}.frame small{display:block;font-size:10px;line-height:1.35;color:#726346;margin-top:7px}.mode{font-size:11px;text-transform:uppercase;letter-spacing:.7px;color:#4b755e}.script{white-space:pre-line;font-size:14px;font-weight:600;border-left:3px solid #9eb87b;padding-left:12px;margin:9px 0 14px}.body p{font-size:13px;margin:9px 0}.overlay{background:#eef2e7;padding:7px 9px;border-radius:5px;font-size:12px}.refgrid{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}.refgrid img{width:100%;border-radius:7px}.refgrid b{font-size:12px}.refgrid p{font-size:12px}.rules{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.rule{padding:18px;background:#fffef9;border-radius:10px}.rule h3{margin:0;font-size:16px}.rule p{font-size:13px}.asset{width:100%;border-collapse:collapse;background:#fffef9;font-size:13px}.asset th,.asset td{padding:12px;text-align:left;vertical-align:top;border-bottom:1px solid #ddd}.footer{font-size:12px;color:#66745e;padding:25px 0}@media(max-width:900px){.grid{grid-template-columns:1fr}.refgrid{grid-template-columns:repeat(3,1fr)}}@media(max-width:520px){.body{grid-template-columns:110px 1fr;gap:12px;padding:12px}.rules{grid-template-columns:1fr}.refgrid{grid-template-columns:repeat(2,1fr)}.bar{font-size:13px}main{padding:20px 12px}}@media print{nav{display:none}.grid{display:block}.card{break-inside:avoid;margin-bottom:15px}.refgrid{grid-template-columns:repeat(3,1fr)}header{padding:24px}.rules{display:block}}'''
parts=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Motilli · Podcast Storyboard</title><style>'+css+'</style><header><div class="eyebrow">Motilli / Director’s spot / Storyboard v1</div><h1>A conversation that shows<br>what’s happening inside.</h1><p>The reference podcast structure, expanded around the full script. Short scientific inserts explain the spoken mechanism; the host and female gastroenterologist carry the story.</p><div class="pills">'+''.join('<span>'+esc(x)+'</span>' for x in [f'{len(beats)} storyboard cards',f'{wc} spoken words',f'~{tc(t)} provisional','9:16 vertical','Script v7 preserved'])+'</div></header><nav><a href="#reference">Reference</a>'+''.join(f'<a href="#s{i}">{i}. {esc(n.split(" · ")[0])}</a>' for i,n in names.items())+'<a href="#production">Production notes</a></nav><main><section id="reference"><div class="eyebrow">What we are matching</div><h2>The reference’s editing grammar</h2><p class="intro">Warm studio, stacked opening, long guest explanations, a listening reaction and direct cuts back to the host’s questions. The reference guest below is male; our planned guest is a female gastroenterologist. These images document framing, not final casting.</p><div class="refgrid">']
for tm,fr,title,desc in ref:parts.append(f'<div><img src="{data(D/"reference"/(fr+".jpg"))}" alt="Reference: {esc(title)}"><b>{tm}<br>{esc(title)}</b><p>{esc(desc)}</p></div>')
parts.append('</div><p class="intro">Source: <a href="'+meta['reference']+'">Instagram reference</a>. Approximately 57 seconds, with five measured scene changes. Our full script is longer; its pacing follows the same conversational logic. All times below are estimates, not final audio alignment.</p></section>')
for sec,name in names.items():
 parts.append(f'<section id="s{sec}"><div class="eyebrow">Chapter {sec:02}</div><h2>{esc(name)}</h2><div class="grid">')
 for b in beats:
  if b['section']!=sec:continue
  parts.append(f'<article class="card" id="{b["id"]}"><div class="bar"><span>{b["id"]} · {b["time"]}</span><span>{b["words"]} words</span></div><div class="body"><div class="frame"><img loading="lazy" src="{data(b["frame"])}" alt="{esc(b["proxy"])}"><small>{esc(b["proxy"])}</small></div><div><div class="mode">{esc(b["mode"])}</div><div class="script">{esc(b["script"])}</div><p><strong>Picture.</strong> {esc(b["visual"])}</p><div class="overlay"><strong>Overlay:</strong> {esc(b["overlay"] or "Captions only")}</div><p><strong>Cut / motion.</strong> {esc(b["edit"])}</p></div></div></article>')
 parts.append('</div></section>')
parts.append('<section id="production"><div class="eyebrow">Editor handoff</div><h2>Production notes</h2><div class="rules">'+''.join(f'<div class="rule"><h3>{esc(k)}</h3><p>{esc(v)}</p></div>' for k,v in notes)+'</div></section><div class="footer">Storyboard v1 · 9 September 2026 · Full script preserved. Proxy images are clearly identified. See asset-list.md for the remaining production shots.</div></main></html>')
(D/'storyboard.html').write_text(''.join(parts))
