import json,sqlite3,csv,hashlib,html,collections
from pathlib import Path
from angle_content import ANGLES
ROOT=Path(__file__).resolve().parents[1];DB=ROOT/'database'
comments=[json.loads(x) for x in (DB/'comments.jsonl').read_text().splitlines()];posts=[json.loads(x) for x in (DB/'posts.jsonl').read_text().splitlines()];cs={c['comment_id']:c for c in comments};ps={p['post_id']:p for p in posts}
quotes=json.loads((ROOT/'report/quote-audit.json').read_text());qm={q['comment_id']:q for q in quotes}
con=sqlite3.connect(DB/'velantra-voc.sqlite');con.execute('DROP TABLE IF EXISTS angles');con.execute('CREATE TABLE angles(angle_key TEXT PRIMARY KEY,title TEXT,priority TEXT,motive TEXT,products TEXT,finding TEXT,application TEXT,counterevidence TEXT,test TEXT,gap TEXT,curated_comment_ids TEXT)')
con.executemany('INSERT INTO angles VALUES (?,?,?,?,?,?,?,?,?,?,?)',[(a['key'],a['title'],a['priority'],a['motive'],a['products'],a['finding'],a['application'],a['counter'],a['test'],a['gap'],json.dumps(a['evidence'])) for a in ANGLES])
con.execute('DROP TABLE IF EXISTS comment_search');con.execute('CREATE VIRTUAL TABLE comment_search USING fts5(comment_id UNINDEXED, post_id UNINDEXED, text, tokenize="unicode61")');con.executemany('INSERT INTO comment_search VALUES (?,?,?)',[(c['comment_id'],c['post_id'],c['text']) for c in comments]);con.commit();con.close()
# Angle-to-comment mapping keeps curation separate from automatic matching.
with (DB/'angle-evidence.csv').open('w',newline='') as f:
 w=csv.writer(f);w.writerow(['angle_key','comment_id','post_id','evidence_type','source_url'])
 for a in ANGLES:
  for cid in a['evidence']:
   c=cs[cid];w.writerow([a['key'],cid,c['post_id'],'analyst_inspected_anchor',c['source_url']])
  for c in comments:
   if a['key'] in c['theme_tags']:w.writerow([a['key'],c['comment_id'],c['post_id'],'automatic_lexical_match',c['source_url']])
with (DB/'angles.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=ANGLES[0].keys());w.writeheader();w.writerows({k:json.dumps(v,ensure_ascii=False) if isinstance(v,list) else v for k,v in a.items()} for a in ANGLES)
# Additive central index; preserve prior contents if one exists.
central=ROOT.parents[1]/'dr-os/voc-index.md';central.parent.mkdir(exist_ok=True)
lines=['---','brand: velantra','artifact: voc-index','generated_by: dr-voc-mining','updated: 2026-09-11','sources:','  - ../voc/2026-09-11-instagram-angle-database/database/posts.csv','  - ../voc/2026-09-11-instagram-angle-database/database/comments.csv','---','','# Velantra voice-of-customer index','','**Golden nugget [INFERRED]: Express personal taste and look well dressed while feeling in control of what the bag costs.**','','The new collection is category-audience research, not a verified Velantra-customer panel. Affordable luxury is the broad position; the entries below are distinct motives or decision contexts.','','[100-page report](../voc/2026-09-11-instagram-angle-database/report/Velantra-Voice-of-Customer-100-Pages.pdf) · [Database guide](../voc/2026-09-11-instagram-angle-database/README.md) · [All 16 angle dossiers](../voc/2026-09-11-instagram-angle-database/angle-dossiers.json)','','## Owned voice of customer','','No verified first-party customer cohort was collected in this social scrape. Do not turn category comments into Velantra testimonials. Historical men’s category research remains separate: [August 2](../voc/2026-08-02-mens-travel-bag-voc.md) and [August 31](../voc/2026-08-31-mens-voc-v2.md).','','## Open conversation','','### Pain and objection map','','Price justification, unfamiliar-brand trust, material skepticism, comfort, fit and availability all appear. Automatic frequencies are available in the report’s evidence screens and are explicitly lexical candidate counts. They are not validated prevalence estimates.','','### Failed-solution library','','Reports include disappointment with particular materials, an expensive purchase rarely used, problems finding the right travel carrying method, and alleged stock/fulfillment mismatches. These are unverified category reports. Consult each linked post before using an allegation.','','### Emotional language','','The report preserves “designer bag ick,” anticipation of styling a new purchase, relief about a preferred material, and resistance to approval from a bag-rating creator. They describe different motives; do not merge them into a single grievance.','','### Community dialect','','Quiet luxury, midluxury, old money, big girl bag and non-logo are contextual terms, not fixed demographic segments. Creator usage is stored separately from audience language.','','### Weak signals','','Founder trust and bag gifting have thin direct evidence. Male-approval messaging is contested. Industry-wide corruption is not established. Those stay as research hypotheses, with dedicated coverage-gap notes.','','## Ranked shortlist for further testing','','Ranking is an analyst judgment, not campaign performance. Scope, urgency and staying power below are qualitative hypotheses; none is a survey score.']
order=['outfit_upgrade','new_brand','designer_spend','logo_independence','old_money','quality_material','work_polish','travel_scale','european_style','euro_trip']
for i,k in enumerate(order,1):
 a=next(a for a in ANGLES if a['key']==k);cid=a['evidence'][0];c=cs[cid];q=qm.get(cid);quote=q['excerpt'] if q else ' '.join(c['text'].split()[:24])
 lines +=['',f'### {i}. {a["title"]}', '',a['motive'],'',f'> {quote}', '',f'Source: [{cid}]({c["source_url"]}), published {c["published_at"][:10]}, retrieved 2026-09-11. Full text and raw locators in the comments database.','',f'Awareness: {"problem/solution" if k in ["designer_spend","quality_material","work_polish","travel_scale"] else "desire/solution"}. Creative potential: {a["priority"]}. Mass instinct: {a["instinct"]}.', '',f'Scope hypothesis: category-relevant, population breadth unmeasured. Urgency hypothesis: {"occasion-led" if k=="euro_trip" else "decision-stage dependent"}. Staying power hypothesis: {"seasonal entry with an evergreen travel motive" if k=="euro_trip" else "potentially renewing wardrobe decision"}.', '',a['application'],'',f'Counterevidence: {a["counter"]}']
lines+=['','## Coverage gaps','','Owned buyer interviews; verified product specifications and present-tense prices; purchase and demographic verification; campaign outcomes; stronger gifting and founder-trust evidence; independent support for any industry-level allegation. Automatic transcripts remain unverified and source frames were not audited.','','Audit: six-month durability is a research hypothesis; seasonal Euro-fall wording is explicitly time-bound. Product swap test remains pending until a specific model and verified proof are selected for an actual ad.']
new='\n'.join(lines)+'\n'
if central.exists() and '2026-09-11-instagram-angle-database' not in central.read_text():central.write_text(central.read_text()+'\n\n'+new)
elif not central.exists():central.write_text(new)
# Plain local searchable interface, with no remote services or publication.
slim=[{k:c[k] for k in ['comment_id','post_id','text','source_url','signal_class','evidence_role','category','platform','likes','theme_tags']}|{'creator':ps.get(c['post_id'],{}).get('creator','')} for c in comments]
(ROOT/'database-browser-data.js').write_text('window.VOC_DATA='+json.dumps(slim,ensure_ascii=False).replace('</','<\\/')+';\n')
(ROOT/'index.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Velantra customer-language database</title>
<style>body{font:16px/1.5 system-ui;margin:32px auto;max-width:1120px;padding:0 20px;color:#202020;background:#fafafa}h1{font-size:30px;margin-bottom:6px}p{max-width:900px}.filters{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}label{display:flex;flex-direction:column;font-size:13px;gap:4px}input,select,button{font:inherit;padding:10px;border:1px solid #aaa;background:white}input{min-width:300px}article{background:white;padding:20px;border-bottom:1px solid #ddd}article p{white-space:pre-wrap;margin:6px 0 12px}.meta{font-size:13px;color:#555}a{color:#285f64}.pill{font-size:12px;margin-right:8px}button{cursor:pointer}#status{margin-bottom:12px}</style>
<h1>Velantra customer-language database</h1><p>16,437 deduplicated comments from Instagram and TikTok. Audience purchase status is unverified. Automatic theme matches help find records; they do not prove a motive or agreement.</p>
<p><a href="report/Velantra-Voice-of-Customer-100-Pages.pdf">100-page report</a> · <a href="README.md">Database guide</a> · <a href="database/comments.csv">Comments CSV</a> · <a href="database/posts.csv">Posts and transcripts</a> · <a href="database/angles.csv">16 angle dossiers</a></p>
<div class="filters"><label>Search comment text<input id="q" placeholder="Try: leather, laptop, never heard"></label><label>Platform<select id="platform"><option value="">Both platforms</option><option>instagram</option><option>tiktok</option></select></label><label>Direct-language theme<select id="theme"><option value="">All themes</option>'''+''.join('<option value="'+a['key']+'">'+html.escape(a['title'])+'</option>' for a in ANGLES)+'''</select></label><label>Screen<select id="screen"><option value="candidate">Substantive handbag-context candidates</option><option value="all">All collected comments</option></select></label></div><p id="status" role="status"></p><main id="results"></main><button id="more">Show 100 more</button>
<script src="database-browser-data.js"></script><script>
const el=id=>document.getElementById(id);let matches=[],limit=100;
function filter(){limit=100;const q=el('q').value.toLocaleLowerCase(),plat=el('platform').value,th=el('theme').value,screen=el('screen').value;matches=VOC_DATA.filter(x=>(!q||x.text.toLocaleLowerCase().includes(q))&&(!plat||x.platform===plat)&&(!th||x.theme_tags.includes(th))&&(screen==='all'||(x.signal_class==='substantive_candidate'&&x.category==='handbag_context'&&x.evidence_role!=='creator_reply')));render()}
function render(){el('results').replaceChildren();el('status').textContent=`${matches.length.toLocaleString()} matching records. Showing ${Math.min(limit,matches.length).toLocaleString()}. Ordered by collection record, not strength of evidence.`;for(const x of matches.slice(0,limit)){const a=document.createElement('article'),p=document.createElement('p'),m=document.createElement('div'),l=document.createElement('a');p.textContent=x.text;m.className='meta';m.textContent=`${x.platform} · ${x.comment_id} · post creator @${x.creator} · ${x.likes} likes · ${x.signal_class} · ${x.evidence_role}`;l.href=x.source_url;l.target='_blank';l.rel='noreferrer';l.textContent='Open source';a.append(p,m,l);el('results').append(a)}el('more').hidden=limit>=matches.length}
for(const id of ['q','platform','theme','screen'])el(id).addEventListener(id==='q'?'input':'change',filter);el('more').onclick=()=>{limit+=100;render()};filter();</script></html>''')
# Immutable run manifest and file integrity inventory.
manifest={'retrieved_at':'2026-09-11','source_scope':'public Instagram and TikTok, seed-led convenience sample','run_count':0,'total_reported_actor_usd':0,'runs':[]}
for f in sorted((ROOT/'raw').glob('*-run.json')):
 d=json.loads(f.read_text());manifest['runs'].append({'wave':f.name[:-9],'id':d['id'],'dataset_id':d['defaultDatasetId'],'status':d['status'],'usd':d.get('usageTotalUsd',0),'startedAt':d.get('startedAt'),'finishedAt':d.get('finishedAt')});manifest['total_reported_actor_usd']+=d.get('usageTotalUsd',0)
manifest['run_count']=len(manifest['runs']);(ROOT/'collection-manifest.json').write_text(json.dumps(manifest,indent=2))
print('Central index:',central);print('FTS rows',len(comments),'angles',len(ANGLES),'displayed exact excerpts',len(quotes))
