local ok,err=pcall(function()
local r=fu:GetResolve();local pm=r:GetProjectManager();local p=pm:GetCurrentProject();assert(not p:IsRenderingInProgress());if p:GetName()~='MOT-UGC-YAPPER-01 v7 V3 20260910' then assert(pm:SaveProject());p=pm:LoadProject('MOT-UGC-YAPPER-01 v7 V3 20260910');assert(p) end;local mp=p:GetMediaPool();local t=nil;for i=1,p:GetTimelineCount() do local q=p:GetTimelineByIndex(i);if q:GetName()=="v27 H1 REBUILD r2 - awaiting HeyGen" or q:GetName()=="v27 H1 FINAL - 1.1x Woman Over40" then t=q end end;assert(t);assert(p:SetCurrentTimeline(t));assert(t:GetEndFrame()==6700)
local clips=t:GetItemListInTrack('video',1);if #clips==0 then
do local m=mp:ImportMedia({"/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27/H1-hook/presenter-avatar-v-30fps.mp4"})[1];assert(m);local c=mp:AppendToTimeline({{mediaPoolItem=m,startFrame=0,endFrame=246,recordFrame=0,trackIndex=1,mediaType=1}})[1];assert(c and c:GetStart()==0 and c:GetEnd()==246);assert(c:SetProperty({ZoomX=1,ZoomY=1,Pan=0,Tilt=0,CropLeft=0,CropRight=0,CropTop=0,CropBottom=0})) end
do local m=mp:ImportMedia({"/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27/H2/presenter-avatar-v-30fps.mp4"})[1];assert(m);local c=mp:AppendToTimeline({{mediaPoolItem=m,startFrame=396,endFrame=6850,recordFrame=246,trackIndex=1,mediaType=1}})[1];assert(c and c:GetStart()==246 and c:GetEnd()==6700);assert(c:SetProperty({ZoomX=1,ZoomY=1,Pan=0,Tilt=0,CropLeft=0,CropRight=0,CropTop=0,CropBottom=0})) end
end;assert(#t:GetItemListInTrack('video',1)==2);assert(#t:GetItemListInTrack('video',2)==24);assert(#t:GetItemListInTrack('video',3)==122);assert(#t:GetItemListInTrack('audio',1)==1);assert(t:GetEndFrame()==6700);assert(t:SetName("v27 H1 FINAL - 1.1x Woman Over40"));t:SetTrackName('video',1,'Fresh HeyGen - Woman Over40 - 1.1x');assert(pm:SaveProject());assert(t:Export("/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27/project-files/Motilli-V27-H1-FINAL.drt",r.EXPORT_DRT));assert(pm:ExportProject(p:GetName(),"/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27/project-files/Motilli-V27-FINAL.drp"));print('V27_FINAL_TIMELINE',t:GetName(),t:GetEndFrame())
p:SetCurrentRenderMode(1);assert(p:SetCurrentRenderFormatAndCodec('mp4','H264'));assert(p:SetRenderSettings({TargetDir="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27/deliverables",CustomName="Motilli-VSL-V27-H1-1.1x",SelectAllFrames=true,ExportVideo=true,ExportAudio=true,FormatWidth=1080,FormatHeight=1920,FrameRate=30,VideoQuality=16000,AudioCodec='aac',AudioBitDepth=16,AudioSampleRate=48000}));local id=p:AddRenderJob();assert(id);print('V27_FINAL_RENDER_JOB',id);local f=io.open('/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27/H1/final-render-job.txt','w');f:write(id);f:close()

end);print('V27_FINALIZE_RESULT',ok,err)
local ok,err=pcall(function()
local r=fu:GetResolve();local pm=r:GetProjectManager();local p=pm:GetCurrentProject();assert(not p:IsRenderingInProgress());if p:GetName()~='MOT-UGC-YAPPER-01 v7 V3 20260910' then assert(pm:SaveProject());p=pm:LoadProject('MOT-UGC-YAPPER-01 v7 V3 20260910');assert(p) end;local mp=p:GetMediaPool();local t=nil;for i=1,p:GetTimelineCount() do local q=p:GetTimelineByIndex(i);if q:GetName()=="v27 H3 REBUILD r2 - awaiting HeyGen" or q:GetName()=="v27 H3 FINAL - 1.1x Woman Over40" then t=q end end;assert(t);assert(p:SetCurrentTimeline(t));assert(t:GetEndFrame()==6911)
local clips=t:GetItemListInTrack('video',1);if #clips==0 then
do local m=mp:ImportMedia({"/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27/H3-hook/presenter-avatar-v-30fps.mp4"})[1];assert(m);local c=mp:AppendToTimeline({{mediaPoolItem=m,startFrame=0,endFrame=458,recordFrame=0,trackIndex=1,mediaType=1}})[1];assert(c and c:GetStart()==0 and c:GetEnd()==458);assert(c:SetProperty({ZoomX=1,ZoomY=1,Pan=0,Tilt=0,CropLeft=0,CropRight=0,CropTop=0,CropBottom=0})) end
do local m=mp:ImportMedia({"/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27/H2/presenter-avatar-v-30fps.mp4"})[1];assert(m);local c=mp:AppendToTimeline({{mediaPoolItem=m,startFrame=396,endFrame=6849,recordFrame=458,trackIndex=1,mediaType=1}})[1];assert(c and c:GetStart()==458 and c:GetEnd()==6911);assert(c:SetProperty({ZoomX=1,ZoomY=1,Pan=0,Tilt=0,CropLeft=0,CropRight=0,CropTop=0,CropBottom=0})) end
end;assert(#t:GetItemListInTrack('video',1)==2);assert(#t:GetItemListInTrack('video',2)==24);assert(#t:GetItemListInTrack('video',3)==126);assert(#t:GetItemListInTrack('audio',1)==1);assert(t:GetEndFrame()==6911);assert(t:SetName("v27 H3 FINAL - 1.1x Woman Over40"));t:SetTrackName('video',1,'Fresh HeyGen - Woman Over40 - 1.1x');assert(pm:SaveProject());assert(t:Export("/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27/project-files/Motilli-V27-H3-FINAL.drt",r.EXPORT_DRT));assert(pm:ExportProject(p:GetName(),"/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27/project-files/Motilli-V27-FINAL.drp"));print('V27_FINAL_TIMELINE',t:GetName(),t:GetEndFrame())
p:SetCurrentRenderMode(1);assert(p:SetCurrentRenderFormatAndCodec('mp4','H264'));assert(p:SetRenderSettings({TargetDir="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27/deliverables",CustomName="Motilli-VSL-V27-H3-1.1x",SelectAllFrames=true,ExportVideo=true,ExportAudio=true,FormatWidth=1080,FormatHeight=1920,FrameRate=30,VideoQuality=16000,AudioCodec='aac',AudioBitDepth=16,AudioSampleRate=48000}));local id=p:AddRenderJob();assert(id);print('V27_FINAL_RENDER_JOB',id);local f=io.open('/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27/H3/final-render-job.txt','w');f:write(id);f:close()

end);print('V27_FINALIZE_RESULT',ok,err)
local p=fu:GetResolve():GetProjectManager():GetCurrentProject();local ids={};for _,h in ipairs({'H1','H3'}) do local f=io.open('/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27'..'/'..h..'/final-render-job.txt','r');table.insert(ids,f:read('*a'));f:close() end;assert(p:StartRendering(ids));print('FINAL_H1_H3_RENDERING')