local ok,err=pcall(function()
local r=fu:GetResolve();local pm=r:GetProjectManager();local p=pm:GetCurrentProject();assert(not p:IsRenderingInProgress());if p:GetName()~='MOT-UGC-YAPPER-01 v7 V3 20260910' then assert(pm:SaveProject());p=pm:LoadProject('MOT-UGC-YAPPER-01 v7 V3 20260910');assert(p) end;local mp=p:GetMediaPool();local O="/Users/brooksorradre2/Documents/marketing brain/brands/motilli/creative/MOT-UGC-YAPPER-01/edit/production-v27";local h="H1";local frames=7370;

local base=nil;local t=nil;local name='v27 '..h..' Woman Over 40 - FINAL 110 percent';local stage='voice110';for i=1,p:GetTimelineCount() do local q=p:GetTimelineByIndex(i);if q:GetName()=='v26 '..h..' Woman Over 40 - cleaned 100 percent r2' then base=q end;if q:GetName()==name then t=q end end;assert(base and base:GetEndFrame()==frames)
if not t then t=mp:CreateEmptyTimeline(name);assert(t and t:GetName()==name);assert(p:SetCurrentTimeline(t));t:SetStartTimecode('00:00:00:00');local c=mp:AppendToTimeline({{mediaPoolItem=base:GetMediaPoolItem(),startFrame=0,endFrame=frames,recordFrame=0,trackIndex=1,mediaType=2}})[1];assert(c and c:GetEnd()==frames);assert(c:SetSpeed({Percentage=110,PitchCorrection=true,RippleTimeline=true})) end
assert(p:SetCurrentTimeline(t));local clips=t:GetItemListInTrack('audio',1);assert(#clips==1);local c=clips[1];local speed=c:GetSpeed();assert(math.abs(speed.Percentage-110)<0.0001 and speed.PitchCorrection==true);assert(math.abs(t:GetEndFrame()-frames/1.1)<=1);assert(base:GetEndFrame()==frames);print('V27_SPEED_VERIFIED',h,t:GetEndFrame());dump(speed)

assert(pm:SaveProject());assert(t:Export(O..'/project-files/Motilli-V27-'..h..'-'..stage..'.drt',r.EXPORT_DRT));p:SetCurrentRenderMode(1);assert(p:SetRenderSettings({ExportVideo=false,ExportAudio=true}));assert(p:SetCurrentRenderFormatAndCodec('mov','H264'));assert(p:SetRenderSettings({TargetDir=O,CustomName=h..'-'..stage..'-master',SelectAllFrames=true,ExportVideo=false,ExportAudio=true,AudioCodec='lpcm',AudioBitDepth=24,AudioSampleRate=48000}));local id=p:AddRenderJob();assert(id);print('V27_JOB',h,stage,id,t:GetEndFrame());assert(pm:SaveProject());assert(pm:ExportProject(p:GetName(),O..'/project-files/Motilli-V27-voices.drp'));p:StartRendering(id)

end);print('V27_RESULT',ok,err)