import csv,json,statistics,shutil,html
from pathlib import Path
P=Path(__file__).resolve().parent;PROJECT=P.parents[1];ROOT=P.parents[5]
# First frame of the incoming image; blur effects begin one frame before these boundaries.
rows=[
(0,'SCIENCE','Colon cutaway with remedy bottles trapped inside','Opening paradox; familiar packages make the problem recognizable. Slow pullback holds one visual through the complete hook.','The color anatomy switches to monochrome pills and red caption backing at the trap line.','HA1/HA2 or HB1/HB2'),
(108,'OBJECT','Monochrome hand holding pills','Concrete remedy overload; red-backed short captions change the visual language after the green hook.','A hard cut returns to a full-body explanatory map when GLP-1 slowdown is named.','S03'),
(150,'SCIENCE','Transparent seated figure with glowing digestive tract','Locate the digestive system while the narrator names the slowdown; glow and gradual enlargement provide motion.','The next shot translates the internal problem into reaching for a laxative.','S04/S05'),
(195,'PEOPLE','Woman on toilet reaches for MiraLAX bottle','Literal reach-for-a-laxative action on the matching words.','A new scale shot lands on temporary success, then a blur reverses that apparent relief.','S06'),
(250,'PEOPLE','Woman standing on bathroom scale','Brief outcome insert under temporary relief; the scale is an association rather than a literal demonstration of bowel relief.','The whip into the mirror punctuates the reversal at the adaptation line.','S11; use time/colon illustration, not scale'),
(285,'PEOPLE','Woman films her abdomen in bathroom mirror','Distress returns; mirror viewpoint makes the problem feel private and familiar.','Another abdomen view maintains subject and central framing across a straight cut.','S12'),
(319,'PEOPLE','Woman holds her abdomen in doorway','Physical sensation stands in for relying on the laxative push.','Head-in-hands bathroom shot escalates from discomfort to frustration.','S12/S13'),
(358,'PEOPLE','Seated woman with head in hands','Human consequence under the weakened-rhythm claim; a tightening crop heightens intensity.','Shorter remedy shots accelerate the escalation.','S14 reframe; keep explanation anatomical'),
(401,'PEOPLE','Woman reads Metamucil container at counter','One brief shot for needing more; product dominates the foreground.','Cut to a larger pile of remedies at the repeated escalation.','S06 named-remedy crops'),
(422,'PEOPLE','Woman lies in bed surrounded by remedies','Escalate from one remedy to an accumulating routine; dark lighting reinforces exhaustion.','Fiber narration begins before the image switches to the colon: a short voiceover lead.','S06/S12'),
(455,'SCIENCE','Colon cross-section with many firm masses','Hold the mechanism explanation long enough to see bulk and limited movement.','Brief blur converts the internal cause into the visible bloating consequence.','S05/S10/S12'),
(536,'PEOPLE','Woman inspects bloated abdomen in mirror','Literal symptom consequence after the anatomy explanation.','Hard cut to a closer face-and-pen shot introduces reassurance about the medication.','S13 anatomy symptom close-up'),
(569,'PEOPLE','Close face with Wegovy pen held near it','Reassurance beat: the body and medication are named together. The depicted pen handling is not a direction to replicate.','Anatomy returns for the restated paradox.','S14/S15 capped pen'),
(626,'SCIENCE','Side-view transparent torso, close framing','Connect the phrase about forcing with internal digestive anatomy.','A hard cut to a wider anatomy view adds a second emphasis within one sentence.','S16'),
(660,'SCIENCE','Wider side-view anatomy with distended abdomen','Second half of the paradox; wider view changes scale while preserving the subject.','The circular toilet action supplies a visual metaphor for the loop.','S16 alternate crop, no body-size change'),
(687,'OBJECT','Top-down swirling toilet bowl','Very short visual punctuation: the loop is represented by circular water motion.','Blur sweeps into the first bright product reveal on the brand name.','S19 pivot; no extra loop line in Motilli copy'),
(706,'PRODUCT','Angled GLP-1 SOS bottle and capsules on bright white','First standalone product reveal; brighter field resets the scene after the problem sequence.','Hard cut from the bottle to an internal demonstration explains the proposed job.','S27, after our three ingredients'),
(756,'SCIENCE','Animated capsule in colon, contents begin moving','A direct product-to-mechanism demonstration. Its exaggerated treatment imagery is source rhetoric, not evidence.','Hard cut to water movement when magnesium is introduced.','S21/S23 concept; no capsule inside organs'),
(815,'SCIENCE','Anatomical cutaway with moving water particles','Names an ingredient and immediately pictures its purported action.','Blur hands the explanation to a smiling human payoff.','S22/S23 soluble fiber'),
(860,'PEOPLE','Woman in cream robe looks relieved in bathroom','Benefit consequence following the water explanation; bright light and relaxed gesture soften the tone.','Two fast reassurance inserts punctuate the short negatives.','S31 then S32'),
(911,'PEOPLE','Smiling woman gestures thumbs-up beside toilet','One short reassurance unit for nothing to force.','Hard cut on the next parallel phrase keeps the cadence crisp.','Use only our script-matched S32–S35'),
(935,'PEOPLE','Woman in green hoodie reacts to her abdomen','Second short reassurance unit; different pose refreshes the picture.','Real ginger enters exactly when the next ingredient is named.','S32–S35 rhythm only'),
(961,'INGREDIENT','Handheld ginger root macro','Tactile real-world ingredient before anatomy; a small hand/camera move maintains energy.','Blur into the digestive illustration bridges ingredient to its proposed action.','S20 celery / S25 chlorophyllin'),
(1008,'SCIENCE','Digestive cutaway with moving yellow contents','Picture the stomach/food language while the contents move; explanation stays concrete.','Hard cut to nutrient imagery starts the next ingredient function.','S21 or S26; use Motilli-specific visuals'),
(1048,'SCIENCE','Transparent torso with nutrient symbols, then glowing whole figure','One continuous changing CGI shot: camera approaches organs, glow spreads, view widens. Do not count each glow or camera move as a cut.','A person holding the bottle makes the daily-use statement tangible.','S29 neutral torso; no vitamin/iron claims copied'),
(1130,'PEOPLE','Pink-haired woman holds bottle toward camera','Daily-use line paired with the product in a hand; expressive face changes the visual texture.','Blur returns abruptly to dark problem footage for the old-remedy objection.','S28 product/gummy detail'),
(1180,'PEOPLE','Woman in pain behind a row of laxatives','Deliberate problem callback after benefits; cool darkness creates contrast.','Hard cut to warm relief at the women/regularity claim.','S30–S31 context; no return to generic reactions'),
(1263,'PEOPLE','Woman smiling on toilet in warm bathroom','Visualizes the regularity testimony; longer hold lets the emotional result register.','Another warm portrait prolongs the relief without an elaborate transition.','S32/S33 imagined daily activities; no borrowed testimonial'),
(1321,'PEOPLE','Warm close-up of older woman with hand on abdomen','Calm, relieved gesture under everyday regularity and escape from the cycle.','Monochrome sweep-away shot resets contrast for the final reframe.','S34/S35'),
(1385,'OBJECT','Monochrome hand sweeps remedies off counter','Action verb becomes a picture: reject the wrong tool; echoes monochrome pills near the opening.','White counter and product shape bridge naturally to a capped GLP-1 pen.','S14 reframe; do not add discarded-medication message'),
(1439,'OBJECT','Ozempic pen on counter with camera push-in','Literal medication object under continuing the shot; the push-in prevents an inert hold.','Hard cut returns to the supplement for the CTA.','S36'),
(1495,'PRODUCT','Bottle placed upright; guarantee seal appears','Brand lands, seal pops/scales up, and the camera tightens. The badge begins before the spoken guarantee.','Blur shifts to a clean locked end card, preserving bottle-centered composition.','S37 product + native CapCut guarantee graphic'),
(1542,'PRODUCT','Centered bottle, capsules, logo, headline and website','Dedicated end-card composition holds through offer and tap instruction; little competing movement.','Hold to the end; no new distracting shot.','S37 clean CTA hold')]
blur={108,285,536,706,860,1008,1180,1542}
raw=json.loads((P/'transcripts/source.json').read_text());words=[w for w in raw['words'] if w.get('type')=='word']
shots=[]
for n,(frame,kind,visual,purpose,flow,mapping) in enumerate(rows):
 end=rows[n+1][0] if n+1<len(rows) else 1651
 cue=' '.join(w['text'] for w in words if frame/25<=((w['start']+min(w['end'],w['start']+.7))/2)<end/25)
 shots.append({'id':f'R{n+1:02d}','start_frame':frame,'end_frame_exclusive':end,'start_s':frame/25,'end_s':end/25,'duration_s':(end-frame)/25,'category':kind,'visual':visual,'voiceover_cue':cue,'purpose':purpose,'flow_to_next':flow,'incoming_transition':'opening' if n==0 else 'horizontal whip / blur' if frame in blur else 'hard cut','transition_core_frames':[frame-1,frame+5] if frame in blur else None,'motilli_mapping':mapping,'representative_frame':min(frame+12,end-1)})
stats={'source_frames':1651,'source_fps':25,'video_duration_s':66.04,'container_duration_s':66.153375,'shots':len(shots),'boundaries':len(shots)-1,'hard_cuts':24,'whip_blur_transitions':8,'mean_shot_s':round(statistics.mean(s['duration_s'] for s in shots),3),'median_shot_s':statistics.median(s['duration_s'] for s in shots),'min_shot_s':min(s['duration_s'] for s in shots),'max_shot_s':max(s['duration_s'] for s in shots),'asr_words':len(words),'overall_words_per_minute':round(len(words)/66.04*60,1),'categories':{k:{'shots':sum(s['category']==k for s in shots),'seconds':round(sum(s['duration_s'] for s in shots if s['category']==k),2)} for k in sorted({s['category'] for s in shots})}}
data={'status':'frame_boundaries_visually_verified','method':'All 1651 frames decoded and differenced; all 32 boundaries inspected on consecutive frames, eight blur spans inspected frame by frame; nine overview sheets cover the entire video. Speech cues from cached ElevenLabs Scribe word timestamps, which are approximate and independent of the measured frame boundaries. Last below word end is overextended by ASR; do not use its 66.0 timestamp as a precise speech endpoint.','boundary_convention':'Zero-based frame index. Hard cut: first incoming frame. Blur: first incoming-image frame; effect starts one frame earlier and mostly resolves about five frames later. End frame exclusive.','stats':stats,'shots':shots}
(P/'reference-cut-map.json').write_text(json.dumps(data,indent=2))
with (P/'reference-cut-map.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=list(shots[0]));w.writeheader();w.writerows(shots)
with (P/'all-frames-index.csv').open('w') as f:
 w=csv.writer(f);w.writerow(['zero_based_frame','time_s','shot','analysis_proxy'])
 for s in shots:
  for i in range(s['start_frame'],s['end_frame_exclusive']):w.writerow([i,f'{i/25:.2f}',s['id'],f'frames/{i:04d}.jpg'])
md=['# GLP-1 SOS reference: frame-accurate editing breakdown','',f"Source: Facebook 1725854202002410. {stats['source_frames']:,} frames at 25 fps; picture runs 66.04 seconds. **33 shots, 24 hard cuts, 8 horizontal blur transitions.** Median shot {stats['median_shot_s']:.2f}s; shortest 0.76s; opening 4.32s; final card 4.36s.",'',data['method'],'',data['boundary_convention'],'','## The actual editing pattern','','The ad uses narration to connect unlike images: a familiar object, an internal explanation, then a human consequence. It changes the picture at a new noun, contrast or repeated phrase. The opening and end card are comparatively slow; the escalation and reassurance inserts can be under a second. That variation creates rhythm. Frequent caption replacements and motion inside shots supply additional visual events without requiring a new clip. Engagement effects here are editorial interpretations; no retention or conversion data was supplied.','','The reference itself includes substantial people footage. Its useful lesson is the role assigned to each image, not simply an anatomy percentage. Motilli keeps the user-requested heavier scientific balance and reserves people for the four everyday activities.','','## Every shot and its connection','','| Shot | Source time | Frames [in,out) | Incoming transition | Narration cue (ASR) | B-roll and purpose | Flow into next shot |','|---|---|---|---|---|---|---|']
for s in shots:md.append(f"| {s['id']} | {s['start_s']:.2f}–{s['end_s']:.2f}s | {s['start_frame']}–{s['end_frame_exclusive']} | {s['incoming_transition']} | {s['voiceover_cue']} | {s['visual']}. {s['purpose']} | {s['flow_to_next']} |")
md+=['','## Transitions, captions and camera movement','','Eight measured incoming-image boundaries: **4.32, 11.40, 21.44, 28.24, 34.40, 40.32, 47.20 and 61.68 seconds**. The outgoing image smears horizontally for one frame; the incoming image appears strongly blurred, then resolves over approximately five more frames. The visibly affected core is about 0.24–0.28 seconds. This describes the rendered appearance; the original preset name and editor settings are unknown. Most boundaries (75%) are straight cuts. No long cross-dissolve, page-turn or decorative 3D transition was observed.','','The blur resets occur at a warning, reversal, mechanism-to-symptom change, product reveal, ingredient-to-action bridge and final card. It is not applied at every picture change. The 41.92–45.20 nutrient shot has large camera moves and light changes inside one shot; these are not separate transitions.','','The opening uses a persistent two-line white uppercase headline on dark green. The next monochrome warning uses short white-on-red chunks. Body captions are mostly short black-on-white rounded rectangles near the lower-middle of the frame. The complete phrases are split into readable units rather than shown as a paragraph. Caption changes often continue across a shot, while the narration remains uninterrupted. The guarantee is its own larger seal, and the final card switches to a stable brand/benefit/URL hierarchy.','','## Voice and audio findings','','Scribe detects 244 spoken word tokens, approximately 222 words/minute over the complete 66.04-second picture. This is a coarse pace measure: hyphenation and the music tail affect the count. Two audio-model passes agree on a brisk, lower-register male voice with an American accent, controlled commercial delivery and crisp emphasis. This is a perceived voice description, not speaker identification or proof of whether the voice is synthetic. The saved Woman Over 40 voice used in the current Motilli draft is not established as the reference voice.','','The narration carries continuously over visual changes. Short pauses and stress make contrasts and repeated clauses land. Quiet electronic pulses and swishes were reported, but the two audio passes disagree about a continuous melodic bed. Treat detailed instrument descriptions, exact SFX events and the first pass’s 160–170 WPM estimate as unverified. Do not copy those into an edit as measured facts. The intended new mix should keep narration dominant and use restrained licensed underscore and brief swishes only at selected visual resets.','','ASR overextends the final word below to 66.0s. Frame timings are exact; spoken endpoint and subtle sound cues still require a listening check during final voice production.','','## Visual balance (measured by shot category)','','| Category | Shots | Seconds |','|---|---:|---:|']
for k,v in stats['categories'].items():md.append(f"| {k} | {v['shots']} | {v['seconds']:.2f} |")
md+=['','## Corrections to the old watch manifest','','The old 31-beat manifest mismatched several image descriptions to timings, omitted the 4.32-second change, grouped/sampled away the 34.40-second change, and misrepresented the ending. Its 44.12-second boundary is internal motion within the nutrient shot. The actual person-with-bottle cut is 45.20s; the final card begins 61.68s and persists through 66.04s. Use the measured map above for planning.','']
(P/'reference-breakdown.md').write_text('\n'.join(md))
print(json.dumps(stats,indent=2))
