local ranges={{[ [=[source_start]=] ]=3,[ [=[source_end]=] ]=68,[ [=[record_start]=] ]=0,[ [=[record_end]=] ]=65},{[ [=[source_start]=] ]=90,[ [=[source_end]=] ]=147,[ [=[record_start]=] ]=65,[ [=[record_end]=] ]=122},{[ [=[source_start]=] ]=150,[ [=[source_end]=] ]=210,[ [=[record_start]=] ]=122,[ [=[record_end]=] ]=182},{[ [=[source_start]=] ]=232,[ [=[source_end]=] ]=299,[ [=[record_start]=] ]=182,[ [=[record_end]=] ]=249},{[ [=[source_start]=] ]=310,[ [=[source_end]=] ]=372,[ [=[record_start]=] ]=249,[ [=[record_end]=] ]=311},{[ [=[source_start]=] ]=389,[ [=[source_end]=] ]=447,[ [=[record_start]=] ]=311,[ [=[record_end]=] ]=369},{[ [=[source_start]=] ]=457,[ [=[source_end]=] ]=493,[ [=[record_start]=] ]=369,[ [=[record_end]=] ]=405},{[ [=[source_start]=] ]=501,[ [=[source_end]=] ]=557,[ [=[record_start]=] ]=405,[ [=[record_end]=] ]=461},{[ [=[source_start]=] ]=579,[ [=[source_end]=] ]=683,[ [=[record_start]=] ]=461,[ [=[record_end]=] ]=565},{[ [=[source_start]=] ]=716,[ [=[source_end]=] ]=822,[ [=[record_start]=] ]=565,[ [=[record_end]=] ]=671},{[ [=[source_start]=] ]=825,[ [=[source_end]=] ]=866,[ [=[record_start]=] ]=671,[ [=[record_end]=] ]=712},{[ [=[source_start]=] ]=892,[ [=[source_end]=] ]=942,[ [=[record_start]=] ]=712,[ [=[record_end]=] ]=762},{[ [=[source_start]=] ]=948,[ [=[source_end]=] ]=963,[ [=[record_start]=] ]=762,[ [=[record_end]=] ]=777},{[ [=[source_start]=] ]=968,[ [=[source_end]=] ]=994,[ [=[record_start]=] ]=777,[ [=[record_end]=] ]=803},{[ [=[source_start]=] ]=1027,[ [=[source_end]=] ]=1171,[ [=[record_start]=] ]=803,[ [=[record_end]=] ]=947},{[ [=[source_start]=] ]=1198,[ [=[source_end]=] ]=1310,[ [=[record_start]=] ]=947,[ [=[record_end]=] ]=1059},{[ [=[source_start]=] ]=1341,[ [=[source_end]=] ]=1383,[ [=[record_start]=] ]=1059,[ [=[record_end]=] ]=1101},{[ [=[source_start]=] ]=1393,[ [=[source_end]=] ]=1431,[ [=[record_start]=] ]=1101,[ [=[record_end]=] ]=1139}}
local output=[=[/Users/brooksorradre2/Documents/marketing brain/brands/velantra/creative/weekender-haaland-mens-2026-09-12/production/resolve-speed110]=]

local pm=r:GetProjectManager();local p=pm:GetCurrentProject();assert(p:GetName()=="VEL_Weekender_Haaland_20260912");assert(not p:IsRenderingInProgress());assert(pm:SaveProject())
local src;for i=1,p:GetTimelineCount() do local t=p:GetTimelineByIndex(i);assert(t:GetName()~="Weekender-Haaland-Gringo-PausesClosed-v2");assert(t:GetName()~="Weekender-Haaland-Gringo-Natural-AvatarV-110-v2");if t:GetName()=="Weekender-Haaland-Gringo-Natural-AvatarV-v2" then src=t end end;assert(src and src:GetEndFrame()==1431)
local pool=p:GetMediaPool();local t=pool:CreateEmptyTimeline("Weekender-Haaland-Gringo-PausesClosed-v2");assert(t);assert(p:SetCurrentTimeline(t));assert(t:SetStartTimecode("00:00:00:00"))
for i,k in ipairs(ranges) do
 local items=pool:AppendToTimeline({{mediaPoolItem=src:GetMediaPoolItem(),startFrame=k.source_start,endFrame=k.source_end,recordFrame=k.record_start}});assert(items)
end
local vs=t:GetItemListInTrack("video",1);local aa=t:GetItemListInTrack("audio",1);assert(#vs==#ranges and #aa==#ranges)
for i,k in ipairs(ranges) do
 for _,x in ipairs({vs[i],aa[i]}) do assert(x:GetStart()==k.record_start and x:GetEnd()==k.record_end,"Native range does not match plan: "..i) end
 assert(t:SetClipsLinked({vs[i],aa[i]},true));assert(t:AddMarker(k.record_start,"Cyan","Speech section "..i,"Synchronized picture, presenter, captions and voice from source frames "..k.source_start.."–"..k.source_end,1))
end
assert(t:GetEndFrame()==1139)
local final=pool:CreateEmptyTimeline("Weekender-Haaland-Gringo-Natural-AvatarV-110-v2");assert(final);assert(p:SetCurrentTimeline(final));assert(final:SetStartTimecode("00:00:00:00"));assert(pool:AppendToTimeline({{mediaPoolItem=t:GetMediaPoolItem(),startFrame=0,endFrame=1139,recordFrame=0}}))
local v=final:GetItemListInTrack("video",1)[1];local a=final:GetItemListInTrack("audio",1)[1];assert(v and a);assert(final:SetClipsLinked({v,a},true));assert(v:SetSpeed({Percentage=110,PitchCorrection=true,RippleTimeline=true}));assert(math.abs(v:GetSpeed().Percentage-110)<0.0001 and math.abs(a:GetSpeed().Percentage-110)<0.0001);assert(v:GetEnd()==a:GetEnd());assert(v:GetSpeed().PitchCorrection and a:GetSpeed().PitchCorrection)
assert(pm:SaveProject());assert(final:Export(output.."/Weekender-Haaland-Gringo-Natural-AvatarV-110-v2.drt",r.EXPORT_DRT));assert(t:Export(output.."/Weekender-Haaland-Gringo-PausesClosed-v2.drt",r.EXPORT_DRT));assert(pm:ExportProject(p:GetName(),output.."/VEL-Weekender-Haaland-Gringo-Speed110-v2.drp",true));r:OpenPage("edit")
return {project=p:GetName(),source=src:GetName(),source_frames=src:GetEndFrame(),trimmed=t:GetName(),kept_frames=t:GetEndFrame(),sections=#vs,timeline=final:GetName(),frames=final:GetEndFrame(),video={start=v:GetStart(),finish=v:GetEnd(),speed=v:GetSpeed()},audio={start=a:GetStart(),finish=a:GetEnd(),speed=a:GetSpeed()},saved=true}
